import {CONTROLLED_P4_ADAPTER,validateControlledConfigurationBinding} from './controlledPublicationBinding.mjs';
import {copy,keys,check,freeze,utc,cycleV2,freezeEvidenceV1} from '../../shared/oceanPublication.mjs';
import {exactJson} from '../exactScientificEvidence.mjs';
import {byteHash,contextKey,contextDescriptor,serializeRankedPublication,readRankedPublication} from './publicationEnvelope.mjs';
export const PUBLISHER_CONFIGURATION='pelora-local-four-hour-publisher-configuration-v1';
export const PUBLISHER_FREEZE='pelora-publication-cycle-freeze-v1';
export const RETAINED_INPUTS='pelora-retained-publication-inputs-v1';
const STEP=14400000;
export function utcBoundary(time){return new Date(Math.floor(Date.parse(utc(time))/STEP)*STEP).toISOString();}
export function nextUtcBoundary(time){return new Date(Date.parse(utcBoundary(time))+STEP).toISOString();}
export function dueBoundaries({effectiveAt,approvedAt,now,after=null,limit}){check(Number.isInteger(limit)&&limit>=1&&limit<=12);const first=Math.ceil(Math.max(Date.parse(utc(effectiveAt)),Date.parse(utc(approvedAt)))/STEP)*STEP,start=after===null?first:Math.max(first,Date.parse(utc(after))+STEP),end=Date.parse(utcBoundary(now));return freeze(Array.from({length:Math.max(0,Math.min(limit,Math.floor((end-start)/STEP)+1))},(_,i)=>new Date(start+i*STEP).toISOString()));}
export function validatePublisherConfiguration(input){
 const c=copy(input);keys(c,['contractVersion','id','context','cycleConfiguration','candidates','scopes','effectiveAt','approvedAt','clockMode','settings','adapterVersion','requireHistoricalReceipt',...(c.adapterVersion===CONTROLLED_P4_ADAPTER?['controlledSupply']:[])]);check(c.contractVersion===PUBLISHER_CONFIGURATION);contextDescriptor(c.context);check(['DATABASE','CONTROLLED_FIXTURE'].includes(c.clockMode));
 c.effectiveAt=utc(c.effectiveAt);c.approvedAt=utc(c.approvedAt);check(c.effectiveAt>=c.approvedAt&&typeof c.requireHistoricalReceipt==='boolean');
 check(['controlled-upstream-fixture-v1','currents-retained-incomplete-explicit-assessment-v1',CONTROLLED_P4_ADAPTER].includes(c.adapterVersion));if(c.adapterVersion==='controlled-upstream-fixture-v1')check(c.clockMode==='CONTROLLED_FIXTURE');
 keys(c.settings,['catchUpCycles','maxConcurrent','maxAttempts','deadlineMs','leaseMs','pollMs','executionTimeoutMs','lookBackMs']);const bounds={catchUpCycles:[1,12],maxConcurrent:[1,4],maxAttempts:[1,5],deadlineMs:[1,172800000],leaseMs:[1000,120000],pollMs:[1000,60000],executionTimeoutMs:[1,120000],lookBackMs:[1,1728000000]};for(const [k,[lo,hi]] of Object.entries(bounds))check(Number.isSafeInteger(c.settings[k])&&c.settings[k]>=lo&&c.settings[k]<=hi);check(c.settings.executionTimeoutMs<c.settings.leaseMs);
 const cycle=cycleV2({scheduledAt:utcBoundary(c.effectiveAt),region:c.context.region,configuration:c.cycleConfiguration});if(c.adapterVersion===CONTROLLED_P4_ADAPTER){check(process.env.PELORA_CP09_P4A_LOCAL==='1'&&process.env.PELORA_TEST_OCEAN_CONDITIONS==='1');validateControlledConfigurationBinding(c);}for(const candidate of c.candidates){if(c.adapterVersion!==CONTROLLED_P4_ADAPTER)keys(candidate,['id','coordinates','eligibility']);check(Array.isArray(candidate.coordinates)&&candidate.coordinates.length===2&&candidate.coordinates.every(Number.isFinite));if(c.adapterVersion!==CONTROLLED_P4_ADAPTER)keys(candidate.eligibility,['eligible']);check(typeof candidate.eligibility.eligible==='boolean');}check(c.candidates.length<=64&&exactJson(c.adapterVersion===CONTROLLED_P4_ADAPTER?c.candidates.map(x=>x.id).sort():c.candidates.map(x=>x.id))===exactJson(cycle.configuration.candidateUniverse.candidateIds)&&cycle.configuration.candidateUniverse.reference.sha256===byteHash(exactJson(c.candidates)));check(c.cycleConfiguration.species.length===1&&c.cycleConfiguration.species[0]==='blue-marlin');
 check(Array.isArray(c.scopes)&&c.scopes.length<=64&&new Set(c.scopes.map(x=>x.candidateId)).size===c.scopes.length);for(const x of c.scopes){keys(x,['candidateId','scope']);check(c.candidates.some(v=>v.id===x.candidateId));keys(x.scope,['manifestDigest','region','product','cellKey']);keys(x.scope.product,['family','provider','dataset','productId']);check(x.scope.product.family==='CURRENTS'&&/^[a-f0-9]{64}$/.test(x.scope.manifestDigest)&&/^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/.test(x.scope.cellKey));check(exactJson(x.scope.region)===exactJson(c.context.region));}
 const {id,...body}=c;check(id==='pcfg1-'+byteHash(exactJson(body)));return freeze(c);
}
export function sealPublisherConfiguration(body){return validatePublisherConfiguration({...body,id:'pcfg1-'+byteHash(exactJson(body))});}
export async function registerLocalPublisherConfiguration(owner,input){
 const c=validatePublisherConfiguration(input),text=exactJson(c),s=(await owner.query("SELECT current_database() AS db,current_setting('listen_addresses') AS listen,inet_server_port() AS port,clock_timestamp() AS now")).rows[0];check(s.db==='pelora_phase3_qualification'&&s.listen==='127.0.0.1'&&s.port===55432);if(c.clockMode==='DATABASE')check(Date.parse(c.approvedAt)>=s.now.getTime()&&Date.parse(c.effectiveAt)>=s.now.getTime());
 await owner.query('BEGIN');try{await owner.query('INSERT INTO cp08.contexts VALUES($1,$2) ON CONFLICT DO NOTHING',[contextKey(c.context),c.context]);check((await owner.query('SELECT count(*)::int AS n FROM cp09.configurations WHERE NOT EXISTS(SELECT 1 FROM cp09.disables WHERE config_id=id)')).rows[0].n<128);await owner.query('INSERT INTO cp09.configurations(id,record_text,digest,context_key,effective_at,approved_at,clock_mode,cycle_template_text) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING',[c.id,text,byteHash(text),contextKey(c.context),c.effectiveAt,c.approvedAt,c.clockMode,exactJson({scheduledAt:"__SCHEDULED_AT__",region:c.context.region,configuration:c.cycleConfiguration})]);check((await owner.query('SELECT record_text FROM cp09.configurations WHERE id=$1',[c.id])).rows[0].record_text===text);await owner.query('COMMIT');}catch(e){await owner.query('ROLLBACK');throw e;}return c;
}
export async function disableLocalPublisherConfiguration(owner,id,at){const local=(await owner.query("SELECT current_database() AS db,current_setting('listen_addresses') AS listen,inet_server_port() AS port")).rows[0];check(local.db==='pelora_phase3_qualification'&&local.listen==='127.0.0.1'&&local.port===55432);await owner.query('BEGIN');try{await owner.query('SELECT 1 FROM cp09.configurations WHERE id=$1 FOR UPDATE',[id]);await owner.query('INSERT INTO cp09.disables(config_id,disabled_at) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,utc(at)]);await owner.query("UPDATE cp09.jobs SET state='disabled',terminal_at=clock_timestamp(),capability=NULL,lease_until=NULL WHERE config_id=$1 AND terminal_at IS NULL",[id]);await owner.query('COMMIT');}catch(e){await owner.query('ROLLBACK');throw e;}}
export function createPublisherLedger({query}){
 const call=async(op,key=null,cap=null,payload=null)=>(await query('SELECT cp09.worker($1,$2,$3,$4) AS value',[op,key,cap,payload])).rows[0].value;
 return Object.freeze({call,configurations:async()=>{const rows=await call('configurations');return rows.map(x=>{check(byteHash(x.recordText)===x.digest);return validatePublisherConfiguration(JSON.parse(x.recordText));});},enumerate:(c,now)=>call('enumerate',c.id,null,c.clockMode==='CONTROLLED_FIXTURE'?utc(now):null),pending:c=>call('pending',c.id),claim:(id,cap)=>call('claim',id,cap),inspect:async id=>{const v=await call('inspect',id);if(v.freezeText)check(byteHash(v.freezeText)===v.freezeDigest);if(v.submissionText){check(byteHash(v.submissionText)===v.submissionDigest);readRankedPublication(v.submissionText);}return freeze(v);},freeze:(id,cap,fence,value)=>call('freeze',id,cap,exactJson({fence,recordText:exactJson(value)})),prepare:(id,cap,fence,p)=>call('prepare',id,cap,exactJson({fence,recordText:serializeRankedPublication(p)})),finalize:(id,cap,fence)=>call('finalize',id,cap,exactJson({fence})),release:(id,cap)=>call('release',id,cap)});
}
export function emptyCycleInput(c,at,lifecycle='delayed'){
 const cycle={scheduledAt:at,region:c.context.region,configuration:c.cycleConfiguration};const entries=cycle.configuration.families.map(family=>({family,status:'UNAVAILABLE',reason:'publisher-no-evaluation',reference:null,product:null,representedAt:null,support:{kind:'unknown',start:null,end:null},qualification:{status:'UNKNOWN',policyReference:'publisher-no-evaluation'},admissibility:{status:'UNASSESSED',policyReference:'publisher-no-evaluation'},assessedAt:at,ageHours:null,qualityReferences:[],lineageReferences:[]}));
 return {context:c.context,cycle,candidates:c.candidates,evidenceFreeze:freezeEvidenceV1(cycleV2(cycle),entries),artifacts:[],searchCounts:{},revision:1,parentId:null,action:'ORIGINAL',lifecycle,reason:'publisher-'+lifecycle};
}
export async function collectRetainedCycleInput(c,at,{reader,clock,signal}){
 check(c.adapterVersion==='currents-retained-incomplete-explicit-assessment-v1'&&c.cycleConfiguration.families.length===1&&c.cycleConfiguration.families[0]==='CURRENTS');const snapshots=[];
 for(const x of c.scopes){signal?.throwIfAborted();const snapshot=await reader.read({scope:x.scope,queryContext:'historical',targetTime:at,sourceTime:{from:new Date(Date.parse(at)-c.settings.lookBackMs).toISOString(),until:new Date(Date.parse(at)+1).toISOString()},maxObservations:1});snapshots.push({candidateId:x.candidateId,snapshot});}
 const constructedAt=utc(clock.now()),content={contractVersion:RETAINED_INPUTS,assessmentCutoff:at,constructedAt,snapshots,requireHistoricalReceipt:c.requireHistoricalReceipt},reference={kind:'captured',contractVersion:RETAINED_INPUTS,referenceId:'rpi1-'+byteHash(exactJson(content)),sha256:byteHash(exactJson(content))};const input=emptyCycleInput(c,at,'completed');
 input.artifacts=[{reference,receivedAt:constructedAt,constructedAt,assessmentCutoff:at,content}];input.evidenceFreeze=freezeEvidenceV1(cycleV2(input.cycle),[{...input.evidenceFreeze.entries[0],status:snapshots.some(s=>s.snapshot.status==='OK')?'AVAILABLE':snapshots.some(s=>!['OK','MISSING'].includes(s.snapshot.status))?'ERROR':'UNAVAILABLE',reason:'retained-reader-snapshots',reference,product:{providerId:'retained-cp07',productId:'CURRENTS',evidenceClass:'recorded-not-requalified'}}]);return input;
}
// This adapter is intentionally incomplete science integration, not operational readiness.
export async function createRetainedCurrentsEvaluator(reference){
 const {buildUnifiedSpeciesOpportunityInterpretationV1}=await import('../server.js');
 return async({binding,candidates,species},readEvidence)=>({binding,results:candidates.map(candidate=>{const retained=readEvidence(reference,candidate.id),entries=retained.snapshots.filter(s=>s.candidateId===candidate.id),source=entries[0]?.snapshot.observations?.[0];if(retained.requireHistoricalReceipt&&source?.provenance.receipt.status!=='AVAILABLE_BY_ASSESSMENT')return {candidate,status:'rejected',reason:'historical-possession-unproven'};return {candidate,status:'fulfilled',value:buildUnifiedSpeciesOpportunityInterpretationV1({assessment:{contractVersion:'pelora-scientific-assessment-v1',assessmentAt:binding.assessmentCutoff},candidate,species,oceanConditions:{currents:source?.evidence.point??null}})};})});
}

export async function createRetainedPublicationRuntime({query,clock={now:()=>new Date().toISOString()},close}){
 check(process.env.PELORA_CP09_LOCAL==='1');const {createOceanStateReader}=await import('./oceanStateReader.mjs'),{createRankedPublicationComposer}=await import('./publicationEnvelope.mjs');const reader=createOceanStateReader({query,clock});return {ledger:createPublisherLedger({query}),collect:(c,at,{signal})=>collectRetainedCycleInput(c,at,{reader,clock,signal}),compose:async(input,c)=>{check(c.adapterVersion==='currents-retained-incomplete-explicit-assessment-v1');const evaluate=input.lifecycle==='completed'?await createRetainedCurrentsEvaluator(input.artifacts[0].reference):async()=>{throw Error('no evaluation for lifecycle record');};return (await createRankedPublicationComposer({evaluate,clock})).compose(input);},close};
}
