import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const migration=new URL('../../supabase/migrations/20261007_captain_entitlement_v1.sql',import.meta.url),read=u=>fs.readFileSync(u,'utf8');
// Test harness replaces only outer migration transaction delimiters with its own rollback-only transaction.
const body=s=>s.replace(/^\s*(?:BEGIN|COMMIT);\s*$/gmi,'');
test('beta access schema static boundaries',()=>{const sql=read(migration);assert.match(sql,/\nBEGIN;/);assert.match(sql,/COMMIT;\s*$/);assert(!sql.includes('service_role'));assert(!sql.includes('365'));assert.match(sql,/first-redemption-utc-calendar-year-v1/);assert.match(sql,/owner_is_authenticated\(user_id\) AND pelora_access.has_current_access/);});
test('isolated PostgreSQL beta schema/RLS qualification',{skip:process.env.PELORA_BETA_SCHEMA_LOCAL!=='1'},async t=>{
 const tooling=process.env.PELORA_EXISTING_PG_TOOLING;if(!tooling)throw Error('existing-pg-tooling-path-required-no-install');const {Client}=createRequire(path.join(tooling,'package.json'))('pg');
 const credential=JSON.parse(read(path.join(process.env.LOCALAPPDATA,'Pelora/PostgreSQL/pelora_phase3_qualification/credentials.json')));
 assert.equal(credential.cluster,'pelora_phase3_qualification');assert.equal(credential.host,'127.0.0.1');assert.equal(Number(credential.port),55432);
 const db=new Client({host:credential.host,port:credential.port,user:credential.username,password:credential.password,database:'pelora_phase3_qualification',connectionTimeoutMillis:3000,query_timeout:10000});await db.connect();
 const q=(s,p=[])=>db.query(s,p),one=async(s,p=[])=>(await q(s,p)).rows[0];const ids=Object.fromEntries(['founder','founding','pending','revoked','beta','other','stranger','expired'].map((n,i)=>[n,'00000000-0000-4000-8000-'+String(i+1).padStart(12,'0')]));
 const actor=async(name,anonymous=false)=>{await q('RESET ROLE');await q("SELECT set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:ids[name],is_anonymous:anonymous})]);await q('SET LOCAL ROLE authenticated');};
 let number=0;async function check(name,fn){await t.test(name,async()=>{await q('RESET ROLE');const save='c'+(++number);await q('SAVEPOINT '+save);try{await fn();}finally{await q('ROLLBACK TO SAVEPOINT '+save);await q('RELEASE SAVEPOINT '+save);}});}
 async function deny(s,p=[],pattern=/row-level security|permission denied|founder-required|beta-only-operation|recipient-mismatch|beta-revoked|original-entitlement-immutable|check constraint|invitation-expired|idempotency-conflict|authenticated-nonanonymous/){await q('SAVEPOINT denial');try{await assert.rejects(q(s,p),pattern);}finally{await q('ROLLBACK TO SAVEPOINT denial');await q('RELEASE SAVEPOINT denial');}}
 const invite=async(email='beta@synthetic.invalid',key=randomUUID())=>{await actor('founder');return (await one('SELECT pelora_access.invite_beta($1,$2) AS v',[email,key])).v;};
 const redeem=async(id,key=randomUUID())=>{await actor('beta');return (await one('SELECT pelora_access.redeem_beta($1,$2) AS v',[id,key])).v;};
 try{
  const free=await one("SELECT to_regnamespace('auth') IS NULL AND to_regnamespace('pelora_access') IS NULL AND to_regclass('public.captain_access') IS NULL AS free");assert(free.free,'synthetic namespace occupied; stop without overwriting');
  await q('BEGIN');await q("DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon NOLOGIN; END IF; IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated NOLOGIN; END IF; END $$");
  await q("CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz);CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT (auth.jwt()->>'sub')::uuid $$;GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.jwt(),auth.uid() TO authenticated;");
  for(const [n,id]of Object.entries(ids))await q('INSERT INTO auth.users VALUES($1,$2,clock_timestamp())',[id,n+'@synthetic.invalid']);
  for(const file of ['20260801_fishing_day_reports_baseline_v1.sql','20260802_ocean_snapshots_v1.sql','20260810_captain_access_v1.sql','20260907_governed_opportunity_history_v1.sql','20260912_governed_opportunity_observation_v1.sql'])await q(body(read(new URL('../../supabase/migrations/'+file,import.meta.url))));
  await q('GRANT USAGE ON SCHEMA public TO authenticated');await q('GRANT SELECT,INSERT ON public.ocean_snapshots TO authenticated');
  for(const n of ['founder','founding','pending','revoked'])await q('INSERT INTO public.captain_access(user_id,access_role,access_status,display_name,boat_name) VALUES($1,$2,$3,$4,$5)',[ids[n],n==='founder'?'founder':'founding_captain',n==='pending'?'pending':n==='revoked'?'revoked':'approved','Synthetic '+n,'Synthetic boat']);
  const before=(await q('SELECT * FROM public.captain_access ORDER BY user_id')).rows;
  await check('migration failure rolls back new schema and lifetime mapping',async()=>{await q('SAVEPOINT invalid_migration');await q('DROP POLICY "Captains can read private ocean snapshots" ON public.ocean_snapshots');await assert.rejects(q(body(read(migration))),/policy-catalog-reconciliation-required/);await q('ROLLBACK TO SAVEPOINT invalid_migration');assert.equal((await one("SELECT to_regnamespace('pelora_access') IS NULL AS absent")).absent,true);assert.deepEqual((await q('SELECT * FROM public.captain_access ORDER BY user_id')).rows,before);});
  await check('late migration failure after DDL/data changes rolls back atomically',async()=>{await q('SAVEPOINT partial_migration');await assert.rejects(q(body(read(migration))+' SELECT 1/0;'),/division by zero/);await q('ROLLBACK TO SAVEPOINT partial_migration');assert.equal((await one("SELECT to_regnamespace('pelora_access') IS NULL AS absent")).absent,true);assert.deepEqual((await q('SELECT * FROM public.captain_access ORDER BY user_id')).rows,before);await q('RELEASE SAVEPOINT partial_migration');});
  await q(body(read(migration)));
  for(const row of before){const after=await one('SELECT * FROM public.captain_access WHERE user_id=$1',[row.user_id]);for(const k of Object.keys(row))assert.deepEqual(after[k],row[k],k);assert.equal(after.entitlement_type,row.access_role==='founder'?'founder_lifetime':'founding_lifetime');assert.equal(after.expires_at,null);}
  await check('founder lifetime remains valid',async()=>{await actor('founder');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,true);});
  await check('founding lifetime remains valid and pending/revoked remain denied',async()=>{for(const n of ['founding','pending','revoked']){await actor(n);assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,n==='founding');}});
  await check('missing access and anonymous founder fail closed',async()=>{await actor('stranger');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);await actor('founder',true);assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);await deny('SELECT pelora_access.invite_beta($1,$2)',['x@synthetic.invalid',randomUUID()]);});
  await check('inactive beta is not a lifetime grant; malformed interval denied',async()=>{await q("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type) VALUES($1,'beta_captain','approved','beta_trial')",[ids.beta]);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);await q('RESET ROLE');await deny("UPDATE public.captain_access SET starts_at=clock_timestamp() WHERE user_id=$1",[ids.beta]);});
  await check('first redemption sets exactly one UTC calendar anniversary',async()=>{const i=await invite(),r=await redeem(i.invitation_id);await q('RESET ROLE');const a=await one('SELECT *,expires_at=pelora_access.anniversary(activated_at) AS exact,starts_at=activated_at AS same FROM public.captain_access WHERE user_id=$1',[ids.beta]);assert(a.exact&&a.same);assert.equal(a.revision,'1');assert.equal(r.revision,1);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,true);});
  await check('leap day and timezone rules deterministic, not fixed 365 days',async()=>{const r=await one("SELECT pelora_access.anniversary('2024-02-29T12:34:56Z') AS leap,pelora_access.anniversary('2023-03-01T12:34:56Z') AS crossing");assert.equal(r.leap.toISOString(),'2025-02-28T12:34:56.000Z');assert.equal(r.crossing.toISOString(),'2024-03-01T12:34:56.000Z');await q("SET LOCAL TIME ZONE 'Pacific/Honolulu'");assert.equal((await one("SELECT pelora_access.anniversary('2024-02-29T12:34:56Z') AS leap")).leap.toISOString(),'2025-02-28T12:34:56.000Z');});
  await check('seven-day window, resend preserves window, reinvite preserves trial',async()=>{const i=await invite();await q('RESET ROLE');assert.equal((await one('SELECT expires_at-created_at=interval \'7 days\' AS exact FROM pelora_access.invitations WHERE invitation_id=$1',[i.invitation_id])).exact,true);await actor('founder');const resend=(await one('SELECT pelora_access.resend_beta($1,$2) AS v',[i.invitation_id,randomUUID()])).v;assert.equal(resend.expires_at,i.expires_at);const original=await redeem(i.invitation_id);const next=await invite();assert.deepEqual(await redeem(next.invitation_id),original);});
  await check('revocation overrides active trial and restoration keeps clock',async()=>{const i=await invite();const original=await redeem(i.invitation_id);await actor('founder');await q("SELECT pelora_access.manage_beta($1,'revoke',$2)",[ids.beta,randomUUID()]);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);const otherInvite=await invite();await actor('beta');await deny('SELECT pelora_access.redeem_beta($1,$2)',[otherInvite.invitation_id,randomUUID()]);await actor('founder');await q("SELECT pelora_access.manage_beta($1,'restore',$2)",[ids.beta,randomUUID()]);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,true);await q('RESET ROLE');const a=await one('SELECT activated_at,expires_at FROM public.captain_access WHERE user_id=$1',[ids.beta]);assert.equal(a.activated_at.toISOString(),new Date(original.activated_at).toISOString());assert.equal(a.expires_at.toISOString(),new Date(original.expires_at).toISOString());});
  await check('wrong recipient and unverified email cannot redeem',async()=>{const i=await invite('other@synthetic.invalid');await actor('beta');await deny('SELECT pelora_access.redeem_beta($1,$2)',[i.invitation_id,randomUUID()]);await q('RESET ROLE');await q('UPDATE auth.users SET email_confirmed_at=NULL WHERE id=$1',[ids.other]);await actor('other');await deny('SELECT pelora_access.redeem_beta($1,$2)',[i.invitation_id,randomUUID()],/verified-recipient-required/);});
  await check('expired invitation is denied',async()=>{const i=await invite();await q('RESET ROLE');await q("UPDATE pelora_access.invitations SET created_at=clock_timestamp()-interval '8 days',expires_at=clock_timestamp()-interval '1 day' WHERE invitation_id=$1",[i.invitation_id]);await actor('beta');await deny('SELECT pelora_access.redeem_beta($1,$2)',[i.invitation_id,randomUUID()]);});
  await check('beta invitation cannot convert lifetime user; beta management cannot change lifetime roles',async()=>{for(const n of ['founder','founding']){const i=await invite(n+'@synthetic.invalid');await actor(n);await deny('SELECT pelora_access.redeem_beta($1,$2)',[i.invitation_id,randomUUID()],/existing-nonbeta-entitlement/);await actor('founder');await deny("SELECT pelora_access.manage_beta($1,'revoke',$2)",[ids[n],randomUUID()]);}});
  await check('ordinary captain cannot invite, self-approve or mutate role/status/expiry',async()=>{const i=await invite();await redeem(i.invitation_id);await actor('beta');for(const statement of ["UPDATE public.captain_access SET access_role='founder'","UPDATE public.captain_access SET access_status='approved'","UPDATE public.captain_access SET expires_at=clock_timestamp()+interval '5 years'","DELETE FROM public.captain_access","INSERT INTO public.captain_access(user_id,access_role,entitlement_type) VALUES(gen_random_uuid(),'founder','founder_lifetime')"]){await deny(statement);}await deny("SELECT pelora_access.manage_beta($1,'approve',$2)",[ids.beta,randomUUID()]);await deny('SELECT pelora_access.invite_beta($1,$2)',['x@synthetic.invalid',randomUUID()]);});
  await check('expiry preserves data and own read/export while writes and cross-owner reads denied',async()=>{await q("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type,activated_at,starts_at,expires_at,start_policy_version) VALUES($1,'beta_captain','approved','beta_trial','2024-02-29T12:00Z','2024-02-29T12:00Z','2025-02-28T12:00Z','first-redemption-utc-calendar-year-v1')",[ids.expired]);for(const n of ['expired','founder'])await q("INSERT INTO public.fishing_day_reports(user_id,trip_date,notes_private) VALUES($1,'2026-01-01','synthetic controlled record')",[ids[n]]);await actor('expired');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);assert.equal((await q('SELECT * FROM public.fishing_day_reports')).rows.length,1);await deny("INSERT INTO public.fishing_day_reports(user_id,trip_date) VALUES($1,'2026-01-02')",[ids.expired]);assert.equal((await q("UPDATE public.fishing_day_reports SET notes_private='changed'")).rowCount,0);assert.equal((await q('DELETE FROM public.fishing_day_reports')).rowCount,0);await q('RESET ROLE');assert.equal((await q('SELECT * FROM public.fishing_day_reports')).rows.length,2);await actor('founder');assert.equal((await q('SELECT * FROM public.fishing_day_reports')).rows.length,1);await deny("INSERT INTO public.fishing_day_reports(user_id,trip_date) VALUES($1,'2026-01-02')",[ids.expired]);});
  await check('original trial dates protected even against a trusted ordinary SQL update',async()=>{const i=await invite();await redeem(i.invitation_id);await q('RESET ROLE');await deny("UPDATE public.captain_access SET expires_at=expires_at+interval '1 year' WHERE user_id=$1",[ids.beta]);});
  await check('idempotent invitation/redemption/revoke events and conflicting request rejected',async()=>{const key=randomUUID(),i=await invite('beta@synthetic.invalid',key);assert.deepEqual(await invite('beta@synthetic.invalid',key),i);await actor('founder');await deny('SELECT pelora_access.invite_beta($1,$2)',['other@synthetic.invalid',key]);const redemption=randomUUID(),r=await redeem(i.invitation_id,redemption);assert.deepEqual(await redeem(i.invitation_id,redemption),r);await actor('founder');const k=randomUUID();const args=[ids.beta,k];const a=(await one("SELECT pelora_access.manage_beta($1,'revoke',$2) AS v",args)).v;assert.deepEqual((await one("SELECT pelora_access.manage_beta($1,'revoke',$2) AS v",args)).v,a);await q('RESET ROLE');assert.equal((await one('SELECT count(*)::int AS n FROM pelora_access.events WHERE actor_id=$1 AND request_id=$2',[ids.founder,k])).n,1);assert.equal((await one('SELECT revision FROM public.captain_access WHERE user_id=$1',[ids.beta])).revision,'2');});
  await check('audit immutable; private tables and internal helper execution denied',async()=>{await actor('founder');for(const s of ['SELECT * FROM pelora_access.events','SELECT * FROM pelora_access.invitations',"UPDATE pelora_access.events SET action='restore'",'DELETE FROM pelora_access.events','SELECT pelora_access.require_founder()'])await deny(s);await q('RESET ROLE');await deny("UPDATE pelora_access.events SET action='restore'",[],/access-event-immutable/);});
  await check('all retained history tables keep owner reads, deny revoked writes and founder cross-owner reads',async()=>{const i=await invite();await redeem(i.invitation_id);await q('RESET ROLE');const fixtures=[['ocean_snapshots',"INSERT INTO public.ocean_snapshots(user_id,snapshot_id,observed_at,latitude,longitude,capture_mode,lifecycle_state,availability_classification,snapshot_schema_version,snapshot_contract_version,snapshot_payload) VALUES($1,$2,clock_timestamp(),25,-90,'simulation','archived','partial','synthetic','synthetic','{}')"],['governed_opportunity_history',"INSERT INTO public.governed_opportunity_history(user_id,history_id,species,opportunity_id,evaluated_at,history_schema_version,history_payload) VALUES($1,$2,'synthetic','synthetic',clock_timestamp(),'synthetic','{}')"],['governed_opportunity_observation',"INSERT INTO public.governed_opportunity_observation(user_id,observation_id,species,candidate_id,evaluated_at,observation_schema_version,observation_payload) VALUES($1,$2,'synthetic','synthetic',clock_timestamp(),'synthetic','{}')"]];for(const [,sql]of fixtures)for(const n of ['beta','founder'])await q(sql,[ids[n],n]);await actor('founder');await q("SELECT pelora_access.manage_beta($1,'revoke',$2)",[ids.beta,randomUUID()]);for(const [table,sql]of fixtures){await actor('beta');assert.equal((await q('SELECT * FROM public.'+table)).rows.length,1);await deny(sql,[ids.beta,'denied']);await actor('founder');assert.equal((await q('SELECT * FROM public.'+table)).rows.length,1);await deny(sql,[ids.beta,'cross-user']);}});
  await check('no PUBLIC/anon execution or runtime object ownership; protected search paths',async()=>{const rows=(await q("SELECT p.proname,p.proconfig,has_function_privilege('anon',p.oid,'EXECUTE') AS anon,has_function_privilege('authenticated',p.oid,'EXECUTE') AS client,owner.rolname AS owner FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles owner ON owner.oid=p.proowner WHERE n.nspname='pelora_access'")).rows;const exposed=['owner_is_authenticated','has_current_access','invite_beta','resend_beta','manage_beta','redeem_beta'];for(const r of rows){assert.equal(r.anon,false,r.proname);assert.equal(r.client,exposed.includes(r.proname));assert(!['anon','authenticated'].includes(r.owner));assert(r.proconfig.includes('search_path=pg_catalog'));}await actor('beta');await deny('CREATE TABLE pelora_access.client_object(id int)');await deny('ALTER FUNCTION pelora_access.has_current_access() RENAME TO forged',[],/must be owner/);});
  await check('invalid timestamp or missing policy does not admit beta',async()=>{for(const value of ['infinity','-infinity'])await deny("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type,activated_at,starts_at,expires_at,start_policy_version) VALUES($1,'beta_captain','approved','beta_trial',$2,$2,$2,'first-redemption-utc-calendar-year-v1')",[ids.beta,value]);await deny("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type,activated_at,starts_at,expires_at) VALUES($1,'beta_captain','approved','beta_trial','2026-10-01','2026-10-01','2027-10-01')",[ids.beta]);});
  await check('founder approval before activation does not start time; lifetime default removed',async()=>{await q("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type) VALUES($1,'beta_captain','pending','beta_trial')",[ids.beta]);await actor('founder');await q("SELECT pelora_access.manage_beta($1,'approve',$2)",[ids.beta,randomUUID()]);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);await q('RESET ROLE');assert.equal((await one('SELECT activated_at FROM public.captain_access WHERE user_id=$1',[ids.beta])).activated_at,null);await deny("INSERT INTO public.captain_access(user_id,entitlement_type) VALUES($1,'founding_lifetime')",[ids.other],/not-null constraint/);});
  await check('expired beta reinvitation and restore never create another free year',async()=>{await q("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type,activated_at,starts_at,expires_at,start_policy_version) VALUES($1,'beta_captain','revoked','beta_trial','2024-02-29T12:00Z','2024-02-29T12:00Z','2025-02-28T12:00Z','first-redemption-utc-calendar-year-v1')",[ids.beta]);await actor('founder');await q("SELECT pelora_access.manage_beta($1,'restore',$2)",[ids.beta,randomUUID()]);const i=await invite();const r=await redeem(i.invitation_id);assert.equal(new Date(r.expires_at).toISOString(),'2025-02-28T12:00:00.000Z');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);});
  await check('transaction rollback after activation restores unredeemed invitation and absent beta',async()=>{const i=await invite();await q('RESET ROLE');await q('SAVEPOINT interrupted_activation');await redeem(i.invitation_id);await q('ROLLBACK TO SAVEPOINT interrupted_activation');await q('RESET ROLE');assert.equal((await q('SELECT * FROM public.captain_access WHERE user_id=$1',[ids.beta])).rows.length,0);assert.equal((await one('SELECT state FROM pelora_access.invitations WHERE invitation_id=$1',[i.invitation_id])).state,'approved');await q('RELEASE SAVEPOINT interrupted_activation');});
  await check('a second verified Auth identity at the same recipient cannot receive another free year',async()=>{const first=await invite();await redeem(first.invitation_id);await q('RESET ROLE');await q('UPDATE auth.users SET email=$1 WHERE id=$2',['beta@synthetic.invalid',ids.other]);const second=await invite();await actor('other');await deny('SELECT pelora_access.redeem_beta($1,$2)',[second.invitation_id,randomUUID()],/recipient-already-bound/);await q('RESET ROLE');assert.equal((await q('SELECT * FROM public.captain_access WHERE access_role=$1',['beta_captain'])).rows.length,1);});
  await check('missing authenticated subject denies current access and activation',async()=>{await q("SELECT set_config('request.jwt.claims','{}',true)");await q('SET LOCAL ROLE authenticated');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);await deny('SELECT pelora_access.redeem_beta($1,$2)',[randomUUID(),randomUUID()]);});
  await check('unknown paid compatibility state grants no access',async()=>{await q("INSERT INTO public.captain_access(user_id,access_role,access_status,entitlement_type,activated_at,starts_at,expires_at,start_policy_version,paid_grant_reference) VALUES($1,'beta_captain','approved','paid_subscription','2026-10-01T00:00Z','2026-10-01T00:00Z','2027-10-01T00:00Z','first-redemption-utc-calendar-year-v1','synthetic-unadmitted')",[ids.beta]);await actor('beta');assert.equal((await one('SELECT pelora_access.has_current_access() AS allowed')).allowed,false);});
 }finally{await q('ROLLBACK');const restored=await one("SELECT to_regnamespace('auth') IS NULL AND to_regnamespace('pelora_access') IS NULL AND to_regclass('public.captain_access') IS NULL AS restored");assert(restored.restored,'rollback-only cleanup failed');await db.end();}
});
