import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {captureCurrentEvidenceV1 as capture,validateCurrentEvidenceCaptureV1 as validate,serializeCurrentEvidenceCaptureV1 as serialize,readCurrentEvidenceCaptureV1 as read,replayCurrentEvidenceSourceV1 as replay,currentCaptureReferenceV1 as ref,captureSampleAgeV1 as age} from '../currentEvidenceCapture.mjs';
import {captureFixture as fixture} from './fixtures/currentEvidenceCaptureFixture.mjs';
import {frame,publication} from './fixtures/temporalEvidenceFixture.mjs';
import {planOceanArchiveWriteV1} from '../../shared/oceanProductArchive.mjs';
import {freezeEvidenceV1,publicationV3,hash} from '../../shared/oceanPublication.mjs';
import {withScientificAssessmentV1} from '../scientificAssessment.mjs';
import {getSeaSurfaceTemperaturePoint,getChlorophyllConditions,getGapFilledChlorophyllConditions,getCurrentConditionsPoint,resolveOpportunityCandidateBathymetryV1} from '../server.js';
import {fixture as candidateFixture} from './fixtures/scientificAssessmentFixture.js';
const assessment={contractVersion:'pelora-scientific-assessment-v1',assessmentAt:'2026-09-24T01:00:00Z'};
for(const [family,assemble] of [['SST',getSeaSurfaceTemperaturePoint],['CHLOROPHYLL_DIRECT',getChlorophyllConditions],['CHLOROPHYLL_GAP_FILLED',getGapFilledChlorophyllConditions],['CURRENTS',getCurrentConditionsPoint]])test(family+' actual current parser source projection equals replay, synthetic transport only',async t=>{
  let transportCalls=0;t.mock.method(globalThis,'fetch',async()=>{transportCalls++;return {ok:true,json:async()=>family==='SST'?{latitude:25.05,longitude:-90.05,current:{time:'2026-09-24T00:00:00Z',sea_surface_temperature:26}}:{table:{columnNames:['time','latitude','longitude','chlor_a','u_current','v_current'],rows:[['2026-09-24T00:00:00Z',25.05,-90.05,0.1,0.5,0.2]]}}};});
  const actual=await assemble(25,-90,assessment);const {ageHours,derived,cache,...source}=actual;
  const f=fixture(family);f.samples[0].point=source;const c=capture(f);const before=transportCalls;const reconstructed=replay(read(serialize(c))).samples[0].point;assert.deepEqual(reconstructed,source);assert.equal(transportCalls,before);
  if(ageHours!==undefined)assert.equal(age(c,'center',assessment),ageHours);
  const rows=[];function leaves(x,path='point'){if(x&&typeof x==='object'){for(const [k,v]of Object.entries(x))leaves(v,path+'.'+k);}else rows.push({field:path,classification:'EXACT_MATCH'});}leaves(source);
  console.log(JSON.stringify({family,comparison:'CURRENT_PARSER_SOURCE_PROJECTION_VS_CAPTURE_REPLAY',rows,excluded:{ageHours:'DERIVED_EQUIVALENT',derived:'UNRESOLVED: current operational description outside source projection',cache:'NONSCIENTIFIC_REQUEST_ONLY'},syntheticTransportOnly:true}));
});
for(const family of ['SST','CHLOROPHYLL_DIRECT','CHLOROPHYLL_GAP_FILLED','CURRENTS']){
  test(family+' exact source field round trip',()=>{const f=fixture(family),c=read(serialize(capture(f)));assert.deepEqual(replay(c),{family,samples:f.samples});assert.deepEqual(c.sourceAuthority,f.sourceAuthority);assert.equal(age(c,'center',assessment),1);});
  test(family+' missing value and unavailable source are not upgraded',()=>{const f=fixture(family),p=f.samples[0].point;for(const k of Object.keys(p))if(['temperatureCelsius','temperatureFahrenheit','concentrationMgM3','speedKnots','directionDegrees','eastwardMetersPerSecond','northwardMetersPerSecond'].includes(k))p[k]=null;if('waterClassification'in p)p.waterClassification=null;p.source.availability='no-valid-pixel';p.observedAt=null;const c=capture(f);assert.deepEqual(replay(c).samples,f.samples);assert.throws(()=>age(c,'center',assessment));});
  test(family+' rejected acquisition remains rejected',()=>{const f=fixture(family);f.samples[0]={role:'center',outcome:'REJECTED',point:null};assert.deepEqual(replay(capture(f)).samples,f.samples);});
}
test('numeric zero is preserved',()=>{const f=fixture('CURRENTS');for(const k of ['speedKnots','directionDegrees','eastwardMetersPerSecond','northwardMetersPerSecond'])f.samples[0].point[k]=0;assert.equal(replay(capture(f)).samples[0].point.speedKnots,0);});
test('SST zero remains numeric and invented land mask is not silently converted',()=>{const f=fixture();f.samples[0].point.temperatureCelsius=0;f.samples[0].point.temperatureFahrenheit=32;assert.equal(replay(capture(f)).samples[0].point.temperatureCelsius,0);f.samples[0].point.mask='land';assert.throws(()=>capture(f));});
test('static bathymetry stays in its existing governed boundary',()=>{const c=candidateFixture().candidate;const a=resolveOpportunityCandidateBathymetryV1(c);assert(a.available);assert.deepEqual(a,resolveOpportunityCandidateBathymetryV1(structuredClone(c)));assert.throws(()=>capture({...fixture(),bathymetry:a}));});
test('nonfinite values and mismatched optional component metadata fail closed',()=>{for(const v of [NaN,Infinity,'0']){const f=fixture();f.samples[0].point.temperatureCelsius=v;assert.throws(()=>capture(f));}const f=fixture('CURRENTS');f.samples[0].point.source.variables.reverse();assert.throws(()=>capture(f));});
test('directional source array preserves asymmetric coordinates values and ordering',()=>{const f=fixture();f.samples=['north','east','south','west'].map((role,i)=>{const p=structuredClone(f.samples[0].point);p.requestedLatitude+=i/10;p.requestedLongitude-=i/20;p.temperatureCelsius+=i;p.temperatureFahrenheit+=i*1.8;return {role,outcome:'FULFILLED',point:p};});const c=capture(f);assert.deepEqual(replay(c).samples,f.samples);f.samples.reverse();assert.notEqual(c.captureId,capture(f).captureId);});
test('duplicate sample role and invented spatial result fail closed',()=>{const f=fixture();f.samples.push(structuredClone(f.samples[0]));assert.throws(()=>capture(f));f.samples.pop();f.samples[0].point.derived={spatialStructure:{}};assert.throws(()=>capture(f));});
test('age and cache metadata are not timeless source truth',()=>{for(const key of ['ageHours','cache']){const f=fixture('CURRENTS');f.samples[0].point[key]=1;assert.throws(()=>capture(f));}const c=capture(fixture('CURRENTS'));assert.equal(age(c,'center',{...assessment,assessmentAt:'2026-09-25T01:00:00Z'}),25);assert.equal(withScientificAssessmentV1(assessment,()=>age(c,'center',assessment)),1);});
test('ambiguous and missing source time captured honestly but cannot be reassessed',()=>{for(const t of [null,'2026-09-24T00:00','malformed']){const f=fixture();f.samples[0].point.observedAt=t;const c=capture(f);assert.equal(replay(c).samples[0].point.observedAt,t);assert.throws(()=>age(c,'center',assessment));}});
test('future evidence is retained as used but cannot be assessed earlier',()=>{const f=fixture();f.samples[0].point.observedAt='2026-09-25T00:00:00Z';assert.throws(()=>age(capture(f),'center',assessment));});
test('provider product substitution rejected; structural success never authenticates a provider',()=>{const f=fixture();f.samples[0].point.source.provider='NOAA-NESDIS-OSPO';assert.throws(()=>capture(f));const c=capture(fixture());assert.equal(c.sourceAuthority.status,'SYNTHETIC_FIXTURE');});
test('unknown family, species output and field rejected',()=>{for(const field of ['species','score','confidence','gate','quality','unknown']){const f=fixture();f[field]='x';assert.throws(()=>capture(f));}const f=fixture();f.family='BATHYMETRY';assert.throws(()=>capture(f));});
for(const name of ['captain_id','userId','Auth UUID','email','boat','origin','range','Fishing Log','catch','lure','bait','privateCoordinates','token','session','missionContext'])test('private field rejected '+name,()=>{for(const position of ['root','source','lineage']){const f=fixture();(position==='root'?f:position==='source'?f.samples[0].point.source:f.lineageReferences[0])[name]='synthetic-private';assert.throws(()=>capture(f));}});
test('metadata and flag privacy are rejected rather than stripped',()=>{for(const value of [{name:'captain identity',value:'synthetic'},{flagId:'session',value:'synthetic'}]){const f=fixture();f.samples[0].point.source.metadata=value;assert.throws(()=>capture(f));}const f=fixture();f.lineageReferences[0].referenceId='captain@example.test';assert.throws(()=>capture(f));});
test('accessors inherited fields and custom array prototypes rejected without getters',()=>{let reads=0;const f=fixture();Object.defineProperty(f.samples[0].point,'observedAt',{enumerable:true,get(){reads++;return 'x';}});assert.throws(()=>capture(f));assert.equal(reads,0);assert.throws(()=>capture(Object.assign(Object.create({token:'x'}),fixture())));const g=fixture();Object.setPrototypeOf(g.samples,Object.create(Array.prototype));assert.throws(()=>capture(g));});
test('detached deep immutability provenance lineage and integrity',()=>{const f=fixture(),c=capture(f);f.samples[0].point.temperatureFahrenheit=99;f.lineageReferences[0].sha256='0'.repeat(64);assert.notEqual(c.samples[0].point.temperatureFahrenheit,99);assert.throws(()=>{c.samples[0].point.source.provider='x';});const bad=structuredClone(c);bad.lineageReferences[0].sha256='0'.repeat(64);assert.throws(()=>validate(bad));});
test('key ordering deterministic; meaningful content and lineage distinguish identities',()=>{const reverse=x=>Array.isArray(x)?x.map(reverse):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).reverse().map(([k,v])=>[k,reverse(v)])):x;const f=fixture(),a=capture(f);assert.deepEqual(a,capture(reverse(f)));f.lineageReferences[0].sha256='0'.repeat(64);const b=capture(f);assert.notEqual(a.captureId,b.captureId);assert.equal(a.scientificContentDigest,b.scientificContentDigest);f.samples[0].point.temperatureFahrenheit++;assert.notEqual(a.scientificContentDigest,capture(f).scientificContentDigest);});
test('canonical read rejects duplicate keys noncanonical JSON and corruption',()=>{const c=capture(fixture()),s=serialize(c);assert.throws(()=>read(s.replace('{','{"family":"SST",')));assert.throws(()=>read(JSON.stringify(c,null,2)));assert.throws(()=>read(s.replace('78.8','79.8')));});
test('replay needs no clock network or Auth',t=>{const c=capture(fixture());t.mock.method(Date,'now',()=>{throw Error('clock forbidden');});t.mock.method(globalThis,'fetch',()=>{throw Error('network forbidden');});assert.deepEqual(replay(read(serialize(c))),replay(c));});
test('archive references capture bytes without pretending capture is a Frame',()=>{const c=capture(fixture()),r=ref(c);assert.equal(r.sha256,hash(c));const p=planOceanArchiveWriteV1(frame(),{writeId:'synthetic',archivedAt:'2026-09-24T01:00:00Z',storageReference:'synthetic',sourceRevision:null,rawEvidence:[{reference:r.referenceId,sha256:r.sha256,availability:'reference-only'}]});assert.equal(p.intent.rawEvidence[0].sha256,r.sha256);assert.throws(()=>planOceanArchiveWriteV1(c,p.intent));});
test('V3 exact captured reference participates in immutable publication evidence',()=>{const p=publication(),r=ref(capture(fixture()));const entries=structuredClone(p.evidence.entries);entries[0].reference=r;const evidence=freezeEvidenceV1(p.cycle,entries);const result=publicationV3({cycle:p.cycle,evidence,history:p.history,attempt:{id:'synthetic-capture-binding',startedAt:p.cycle.scheduledAt,endedAt:p.cycle.scheduledAt},evaluation:{...p.evaluation,evidenceSetId:evidence.evidenceSetId}});assert.deepEqual(result.evidence.entries[0].reference,r);});
test('24-group audit remains complete and source qualification is not claimed',()=>{const m=JSON.parse(readFileSync(new URL('../../docs/Current_Product_Capture_Matrix_v1.json',import.meta.url),'utf8'));assert.equal(m.groups.length,24);assert(m.outsideQualifiedSubset.length>0);});

// Final adversarial review: existing science is not invoked to hide input differences.
for(const marker of ['observationType','algorithm','resolutionKilometers','experimental'])test('review: missing reconstruction marker rejected '+marker,()=>{const f=fixture('CHLOROPHYLL_GAP_FILLED');delete f.samples[0].point.source[marker];assert.throws(()=>capture(f));});
test('review: SST age requires retained valid-time provenance',()=>{for(const marker of [null,undefined]){const f=fixture();if(marker===undefined)delete f.samples[0].point.timestampProvenance;else f.samples[0].point.timestampProvenance=marker;const c=capture(f);assert.throws(()=>age(c,'center',assessment));}});
const families=['SST','CHLOROPHYLL_DIRECT','CHLOROPHYLL_GAP_FILLED','CURRENTS'];
for(const from of families)for(const to of families)if(from!==to)test('review: family substitution '+from+' -> '+to,()=>{const f=fixture(from);f.family=to;assert.throws(()=>capture(f));});
for(const [field,value] of [['provider','another-provider'],['dataset','another-dataset'],['classification','satellite-observation'],['observationType','direct-satellite'],['algorithm','another-algorithm'],['revision','invented']])test('review: source metadata substitution '+field,()=>{const f=fixture('CHLOROPHYLL_GAP_FILLED');f.samples[0].point.source[field]=value;assert.throws(()=>capture(f));});
for(const family of families)test('review: zero null and unsupported missing reasons '+family,()=>{
  const f=fixture(family),p=f.samples[0].point;for(const k of Object.keys(p))if(['temperatureCelsius','temperatureFahrenheit','concentrationMgM3','speedKnots','directionDegrees','eastwardMetersPerSecond','northwardMetersPerSecond'].includes(k))p[k]=0;
  assert.deepEqual(replay(capture(f)).samples,f.samples);
  for(const missing of ['land','masked','provider-no-data','invented']){const bad=structuredClone(f);bad.samples[0].point.missingReason=missing;assert.throws(()=>capture(bad));}
  const bad=structuredClone(f);const numeric=Object.keys(p).find(k=>typeof p[k]==='number'&&!k.endsWith('Latitude')&&!k.endsWith('Longitude'));bad.samples[0].point[numeric]=null;assert.throws(()=>capture(bad));
});
for(const state of ['unavailable','no-valid-pixel','provider-unavailable','request-failed'])test('review: captured availability never upgraded '+state,()=>{const f=fixture();f.samples[0].point.source.availability=state;const c=capture(f);assert.equal(replay(c).samples[0].point.source.availability,state);assert.notEqual(c.captureId,capture(fixture()).captureId);});
test('review: unsupported quality and private flag channels reject at every level',()=>{for(const location of ['root','point','source','lineage'])for(const quality of [null,{state:'good'},{flagId:'captainId',value:'synthetic'},{name:'token',value:'synthetic'}]){const f=fixture(),target=location==='root'?f:location==='point'?f.samples[0].point:location==='source'?f.samples[0].point.source:f.lineageReferences[0];target.quality=quality;assert.throws(()=>capture(f));}});
for(const boundary of ['validate','serialize','replay','reference','age'])test('review: hostile descriptors rejected by '+boundary,()=>{const invoke={validate,serialize,replay,reference:ref,age:x=>age(x,'center',assessment)}[boundary];for(const getter of [true,false]){let reads=0;const c=structuredClone(capture(fixture()));Object.defineProperty(c.samples[0].point.source,'provider',{enumerable:true,...(getter?{get(){reads++;throw Error('getter');}}:{set(){reads++;}})});assert.throws(()=>invoke(c));assert.equal(reads,0);}});
test('review: prototype keys toJSON valueOf and symbols are never authority',()=>{for(const key of ['__proto__','constructor','prototype','toJSON','valueOf']){const f=fixture();Object.defineProperty(f.samples[0].point,key,{enumerable:true,value:'synthetic'});assert.throws(()=>capture(f));}const f=fixture();f[Symbol('token')]='synthetic';assert.throws(()=>capture(f));});
test('review: mutations of every current vector field invalidate retained identity',()=>{const c=capture(fixture('CURRENTS'));for(const k of ['speedKnots','directionDegrees','eastwardMetersPerSecond','northwardMetersPerSecond','requestedLatitude','requestedLongitude','resolvedLatitude','resolvedLongitude']){const bad=structuredClone(c);bad.samples[0].point[k]+=0.1;assert.throws(()=>validate(bad));const f=fixture('CURRENTS');f.samples[0].point[k]+=0.1;assert.notEqual(c.captureId,capture(f).captureId);}});
test('review: timestamp replacement cannot reuse captured identity',()=>{const c=capture(fixture());for(const t of [assessment.assessmentAt,'2026-09-22T12:00:00Z','2026-09-24T00:59:00Z']){const bad=structuredClone(c);bad.samples[0].point.observedAt=t;assert.throws(()=>validate(bad));}for(const key of ['acquiredAt','retrievedAt','assessmentAt','nominalTime']){const f=fixture();f.samples[0].point[key]='2026-09-24T00:00:00Z';assert.throws(()=>capture(f));}});
test('review: future invalid calendar and timezone ambiguity have no scientific age',()=>{for(const t of ['2026-09-24T01:00:00.001Z','2026-02-30T00:00:00Z','2026-09-24T00:00:00+00:00','2026-09-24T00:00:00']){const f=fixture();f.samples[0].point.observedAt=t;assert.throws(()=>age(capture(f),'center',assessment));}});
test('review: replay output is detached deeply frozen and raw capture stable across reassessment',()=>{const c=capture(fixture()),raw=serialize(c),a=replay(c),b=replay(c);assert.notEqual(a.samples,b.samples);assert.throws(()=>{a.samples[0].point.observedAt='x';});assert.throws(()=>{a.samples.push(a.samples[0]);});assert.equal(age(c,'center',assessment),1);assert.equal(age(c,'center',{...assessment,assessmentAt:'2026-09-25T01:00:00Z'}),25);assert.equal(serialize(c),raw);});
test('review: source qualification cannot be upgraded by capture status',()=>{const f=fixture();f.sourceAuthority.status='QUALIFIED';assert.throws(()=>capture(f));f.sourceAuthority.status='RECORDED_NOT_REQUALIFIED';assert.equal(capture(f).sourceAuthority.status,'RECORDED_NOT_REQUALIFIED');});
test('review: matrix classifications and retained 62 leaf comparisons verified',()=>{const m=JSON.parse(readFileSync(new URL('../../docs/Current_Product_Capture_Matrix_v1.json',import.meta.url),'utf8'));const counts={};m.groups.forEach(g=>counts[g.classification]=(counts[g.classification]??0)+1);assert.deepEqual(counts,{GOVERNED_EXISTING_CONTRACT:3,FROZEN_CAPTURE_REQUIRED:7,DERIVABLE_FROM_FROZEN_GOVERNED_SOURCE:7,UNRESOLVED:3,SPECIES_CONFIGURATION:1,OPERATIONAL_REQUEST_ONLY:2,CAPTAIN_PROJECTION:1});const rows=m.sourceProjectionComparisons.flatMap(c=>c.rows);assert.equal(rows.length,62);assert(rows.every(r=>r.classification==='EXACT_MATCH'));});
test('review: asymmetric current vectors preserve roles coordinates and components through reordering',()=>{const f=fixture('CURRENTS'),base=f.samples[0].point;f.samples=['north','east','south','west'].map((role,i)=>({role,outcome:'FULFILLED',point:{...structuredClone(base),requestedLatitude:25+i/10,requestedLongitude:-90-i/20,eastwardMetersPerSecond:i-2,northwardMetersPerSecond:3-i,speedKnots:i+0.5,directionDegrees:i*70}}));const c=capture(f);assert.deepEqual(replay(read(serialize(c))).samples,f.samples);const changed=structuredClone(c);[changed.samples[0],changed.samples[1]]=[changed.samples[1],changed.samples[0]];assert.throws(()=>validate(changed));f.samples.reverse();assert.notEqual(c.captureId,capture(f).captureId);f.samples.pop();assert.notEqual(c.captureId,capture(f).captureId);});
