import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {runDefault,differences} from './fixtures/defaultProviderTransitiveFixture.mjs';
import {source,coverageSession,branchCount,discoverDefaultGraph} from './fixtures/defaultProviderGraphReview.mjs';
const evidence=[],clockBase=Date.parse('2052-01-01');let tick=0,profiler,baseline;
after(async()=>{if(profiler)await profiler.close();if(process.env.PELORA_WRITE_DEFAULT_REVIEW==='1')writeFileSync('.local/ocean-quarantine/task12b6q/evidence.json',JSON.stringify(evidence,null,2)+'\n');});
async function run(t,mode,options={}){profiler??=await coverageSession();const result=await runDefault(t,{mode,clock:clockBase+86400000*tick++,...options});result.coverage=await profiler.take();return result;}
test('production species orchestration binds private default at both governed classes',()=>{const start=source.indexOf('async function evaluateControlledGulfBlueMarlinV1AtAssessment('),end=source.indexOf('async function getDynamicBlueMarlinOpportunities',start);assert(start>=0&&end>start);assert.equal((source.slice(start,end).match(/oceanConditionsProvider:\s*getOceanConditions/g)||[]).length,2);assert(!/^export (?:async )?function getOceanConditions\(/m.test(source));});
test('coordinate box is enforced before actual default transport',async t=>{for(const coordinates of [[25,-90],[15,-100],[32,-75]]){const r=await run(t,'complete',{coordinates});assert(r.requests.length>0);assert.equal(r.ocean.observationSnapshot.available,true);}for(const coordinates of [[14.999999,-90],[32.000001,-90],[25,-100.000001],[25,-74.999999]]){const r=await run(t,'complete',{coordinates});assert.equal(r.leaf.reason,'candidate-coordinates-invalid');assert.equal(r.requests.length,0);}evidence.push({id:'coordinate-box',inside:[[25,-90],[15,-100],[32,-75]],outsideRejectedBeforeTransport:true});});
test('complete baseline executes unchanged default snapshot chain',async t=>{baseline=await run(t,'complete');assert.equal(baseline.ocean.observationSnapshot.available,true);assert.equal(baseline.ocean.oceanEvidence.groups.productivity.available,true);assert.equal(baseline.ocean.sst.derived.spatialStructure.samples.length,4);evidence.push({id:'complete',requests:baseline.requests.map(x=>x.role),snapshotAvailable:true});});
test('empty chlorophyll is parsed as no-valid-pixel then normalized unavailable',async t=>{const r=await run(t,'empty-chlorophyll');assert.equal(r.ocean.chlorophyll.concentrationMgM3,null);assert.equal(r.ocean.chlorophyll.source.availability,'unavailable');assert.equal(r.ocean.oceanEvidence.groups.productivity.available,false);assert.equal(r.ocean.observationSnapshot.available,true);assert(branchCount(r.coverage,'getChlorophyllConditionsAtAssessment','"no-valid-pixel"')>0);assert.equal(branchCount(baseline.coverage,'getChlorophyllConditionsAtAssessment','"no-valid-pixel"'),0);const start=source.indexOf('const chlorophyllConcentrationMgM3 =',source.indexOf('function buildSurfaceWaterCharacterAnalysis('));const offset=source.indexOf(': null;',start)+2;const at=c=>c.flatMap(f=>f.ranges).filter(x=>x.startOffset<=offset&&x.endOffset>offset).sort((a,b)=>(a.endOffset-a.startOffset)-(b.endOffset-b.startOffset))[0]?.count;assert(at(r.coverage)>0);assert.equal(at(baseline.coverage),0);evidence.push({id:'empty-chlorophyll',stableBranch:'buildSurfaceWaterCharacterAnalysis::chlorophyll-concentration::nonfinite-null',historicalLine:source.slice(0,offset).split('\n').length,positiveCoverage:at(r.coverage),controlCoverage:at(baseline.coverage),finalAvailability:'unavailable',productivityAvailable:false,snapshotAvailable:true});});
test('future SST rejects whole assembly, distinct from individual request rejection',async t=>{const r=await run(t,'future-sst'),s=r.ocean.sst.derived.spatialStructure;assert(branchCount(r.coverage,'assessSstTransitionConfidence','"SST evidence timestamp after scientific assessment"')>0);assert.deepEqual(s.samples,[]);assert.equal(s.coverage,'unavailable');assert(!Object.hasOwn(s,'orientation'));assert(!Object.hasOwn(s,'confidence'));assert(branchCount(r.coverage,'getOceanConditionsAtAssessment','"spatial-sampling-unavailable"')>0);assert.equal(branchCount(baseline.coverage,'getOceanConditionsAtAssessment','"spatial-sampling-unavailable"'),0);evidence.push({id:'future-sst',samples:0,coverage:s.coverage,orientationPresent:false,confidencePresent:false,positiveFallbackCoverage:true});const missing=await run(t,'rejected-sst'),m=missing.ocean.sst.derived.spatialStructure;assert(branchCount(missing.coverage,'getSstSpatialStructureAtAssessment','"request-failed"')>0);assert.equal(m.samples.length,4);assert(m.samples.every(x=>x.source.availability==='request-failed'));assert.equal(m.coverage,'insufficient');assert(Object.hasOwn(m,'orientation'));assert(Object.hasOwn(m,'confidence'));evidence.push({id:'rejected-sst',samples:4,coverage:m.coverage,orientationPresent:true,confidencePresent:true});});
test('empty currents and rejected weather preserve distinct downstream states',async t=>{const c=await run(t,'empty-currents');assert(branchCount(c.coverage,'getCurrentConditionsPointAtAssessment','"no-valid-pixel"')>0);assert.equal(c.ocean.currents.speedKnots,null);assert.equal(c.ocean.observationSnapshot.available,true);const w=await run(t,'rejected-weather');assert(branchCount(w.coverage,'getMarineConditions','"provider-request-failed"')>0);assert.equal(w.ocean.dataQuality.layers.wind.state,'degraded');assert.equal(w.ocean.observationSnapshot.available,true);evidence.push({id:'empty-currents',currentAvailability:c.ocean.currents.source.availability,speedKnots:null},{id:'rejected-weather',windState:'degraded'});});
test('cache hit and expiry comparisons retain exact differences without stripping authority',async t=>{const clock=Date.parse('2060-01-01');const cold=await runDefault(t,{clock}),warm=await runDefault(t,{clock:clock+1000}),expired=await runDefault(t,{clock:clock+86400000});assert(warm.requests.length<cold.requests.length);assert.equal(expired.requests.length,cold.requests.length);const d=differences(cold.ocean.observationSnapshot,warm.ocean.observationSnapshot);assert(d.some(x=>x.path.endsWith('/cache/status')&&x.left==='miss'&&x.right==='hit'));assert(d.every(x=>x.path==='/generatedAt'||/\/cache\/(status|ageSeconds)$/.test(x.path)));assert(differences(cold.ocean.observationSnapshot,expired.ocean.observationSnapshot).every(x=>x.path==='/generatedAt'));evidence.push({id:'cold-warm-expiry',requests:[cold.requests.length,warm.requests.length,expired.requests.length],differences:d,scope:'one complete represented source case; no general cache equivalence claim'});});
test('source closure reproduces independently but does not qualify member effects or branches',()=>{const graph=discoverDefaultGraph();assert.deepEqual(discoverDefaultGraph(),graph);assert.equal(graph.nodes.length,154);assert.equal(graph.callbacks.length,33);assert.equal(graph.unresolvedNamedTargets.length,0);assert.equal(graph.semanticGraphComplete,false);assert.equal(graph.semanticBranchUniverseEstablished,false);for(const name of ['getOceanConditionsAtAssessment','getSstSpatialStructureAtAssessment','getChlorophyllConditionsAtAssessment','getCurrentConditionsPointAtAssessment','getMarineConditions','buildObservationSnapshot'])assert(graph.nodes.some(n=>n.function===name));assert(graph.memberCallReview.remainingEffectExamples.some(x=>x.inlineCallbacks.length));const path=new URL('../../docs/Default_Provider_Transitive_Discovery_v2.json',import.meta.url);if(process.env.PELORA_WRITE_DEFAULT_REVIEW==='1')writeFileSync(path,JSON.stringify(graph,null,2)+'\n');else assert.deepEqual(JSON.parse(readFileSync(path)),graph);});

test('review explicitly blocks authority work and does not invent completeness counts',()=>{const r=JSON.parse(readFileSync(new URL('../../docs/Default_Provider_Transitive_Review_v1.json',import.meta.url)));assert.equal(r.verdict,'DEFAULT_PROVIDER_SEMANTIC_BRANCH_MODEL_UNRESOLVED');assert.equal(r.qualified,false);assert.equal(r.graph.complete,false);assert.equal(r.branchReview.semanticUniverseTotal,null);assert.equal(r.branchReview.openReviewObligations.length,9);assert(r.branchReview.openReviewObligations.every(x=>x.disposition==='REQUIRES_FURTHER_REVIEW'));assert.equal(r.producerInventory.created,false);assert.equal(r.authorityProposalCreated,false);assert.equal(r.authorityFreezeCreated,false);assert.equal(r.projectionV3Created,false);});
test('preservation record does not make failed files runtime test dependencies',()=>{const r=JSON.parse(readFileSync(new URL('../../docs/Default_Provider_Transitive_Preservation_v1.json',import.meta.url)));assert.equal(r.files.length,41);assert.equal(new Set(r.files.map(x=>x.path)).size,41);for(const x of r.files){assert.match(x.before,/^[a-f0-9]{64}$/);assert.equal(x.before,x.after);assert.equal(x.unchanged,true);}});

test('six bounded default cases are stable under reverse, five seeded permutations, duplicates and warm runs',async t=>{
 const modes=['complete','empty-chlorophyll','future-sst','rejected-sst','empty-currents','rejected-weather'];
 const permitted=new Set(['/generatedAt','/observations/currents/cache/status','/observations/currents/cache/ageSeconds']);
 for(let i=0;i<4;i++)for(const prefix of [`/observations/sst/derived/spatialStructure/samples/${i}`,`/observations/currents/derived/spatialAnalysis/spatialStructure/vectors/${i}`,`/evidence/groups/current/spatialAnalysis/spatialStructure/vectors/${i}`])for(const key of ['status','ageSeconds'])permitted.add(prefix+'/cache/'+key);
 const orders=[modes,[...modes].reverse()];for(let seed=1;seed<=5;seed++){const order=[...modes];let state=seed;for(let i=order.length-1;i>0;i--){state=(Math.imul(state,1664525)+1013904223)>>>0;const j=state%(i+1);[order[i],order[j]]=[order[j],order[i]];}orders.push(order);}orders.push([...modes,modes[0],modes[3],modes[5],modes[0]],modes.slice(0,2),[...modes]);
 const expected=new Map();let execution=0;let runs=0;
 for(const order of orders)for(const mode of order){const clock=Date.parse('2070-01-01')+(execution++)*86400000;const cold=await runDefault(t,{mode,clock,coordinates:[25,-90]}),warm=await runDefault(t,{mode,clock:clock+1000,coordinates:[25,-90]});runs+=2;const snapshot=cold.ocean.observationSnapshot;if(!expected.has(mode))expected.set(mode,snapshot);for(const other of [snapshot,warm.ocean.observationSnapshot]){const delta=differences(expected.get(mode),other);assert(delta.every(x=>permitted.has(x.path)),JSON.stringify({mode,delta}));}}
 evidence.push({id:'bounded-order-cache-attacks',scenarioCount:modes.length,orders:orders.length,runs,exactOperationalDifferencePaths:[...permitted].sort(),allOtherSnapshotLeavesExactlyEqual:true,inventoryOrAuthorityClaim:false});
});

test('bounded comparison preserves signed zero, key presence and array structure',()=>{assert.equal(differences({x:-0},{x:+0}).length,1);assert.equal(differences({x:null},{}).length,1);assert.equal(differences({x:undefined},{}).length,1);assert(differences([,],[]).length>0);assert(differences([1,2],[2,1]).length>0);assert.deepEqual(differences({b:2,a:1},{a:1,b:2}),[]);});
