// Offline presentation qualification; uses only retained, verified evidence.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {retainedField} from '../../review/noaa-sst-pilot/scaleReview.mjs';
import {distribution,candidateScales,percentile,fahrenheit,kelvin,scaleColor,scalePolicy,scaleTile,inspectCell} from '../../review/noaa-sst-pilot/scales.mjs';
import {tileIdentity,sourceIndex,lonLat} from '../../review/scalar-tiles/presentationTiles.mjs';
import {sstColor} from '../../frontend/src/utils/syntheticSstDisplay.js';
const {field}=await retainedField(),before=JSON.stringify(field),stats=distribution(field),scales=candidateScales(field);
let count=0;const test=(name,fn)=>{fn();count++;console.log(`PASS ${name}`);};
test('deterministic full-field statistics/domain',()=>{assert.deepEqual(candidateScales(field),scales);assert.deepEqual(distribution(field),stats);});
test('absolute Fahrenheit/Kelvin conversion',()=>{assert.equal(fahrenheit(273.15),32);assert.equal(kelvin(86),303.15);assert.equal(fahrenheit(0),-459.66999999999996);assert.throws(()=>fahrenheit(null));});
test('type 7 quantile interpolation and endpoints',()=>{assert.equal(percentile([0,10,20,30],.25),7.5);assert.equal(percentile([0,10],0),0);assert.equal(percentile([0,10],1),10);assert.equal(percentile([2,2,2],.98),2);});
test('invalid quantile input fails',()=>{for(const a of [[],[2,1],[null],[NaN]])assert.throws(()=>percentile(a,.5));assert.throws(()=>percentile([1],2));});
test('standard deviation uses difference-unit conversion',()=>{assert.equal(stats.statistics.standardDeviation.F,stats.statistics.standardDeviation.K*1.8);assert.ok(stats.statistics.standardDeviation.F<1);});
test('missing cells excluded from distribution',()=>{assert.equal(stats.count,71896);assert.equal(stats.missing,21704);assert.equal(stats.histogram.reduce((s,b)=>s+b.count,0),stats.count);});
test('known control saturation',()=>{assert.equal(scales[0].clipping.high,61248);assert.equal(scales[0].clipping.low,0);});
test('fixed and full-frame domains have no clipping',()=>{assert.deepEqual(scales[1].domainF,[70,95]);assert.deepEqual(scales[2].domainF,[82,89]);assert.equal(scales[1].clipping.total,0);assert.equal(scales[2].clipping.total,0);});
test('outward domain expands for hotter/cooler complete frames',()=>{for(const [values,expected] of [[[79.6,90.4],[79,91]],[[74.2,84.7],[74,85]],[[88.1,92.3],[88,93]]]){const example={deliveryId:'synthetic-domain-example',grid:{values:values.map(kelvin),missing:[null,null]}};const c=candidateScales(example).find(s=>s.id==='frame');assert.deepEqual(c.domainF,expected);assert.equal(c.clipping.total,0);}});
test('robust thresholds exact K and strict-tail clipping counts',()=>{assert.deepEqual(scales[3].domainK,[stats.statistics.p02.K,stats.statistics.p98.K]);assert.equal(scales[3].clipping.low,1430);assert.equal(scales[3].clipping.high,1335);});
test('viewport cannot alter scale selection',()=>{assert.deepEqual(candidateScales(field,{bounds:[-98,18,-80,31],zoom:4}),candidateScales(field,{bounds:[-88,29,-87,30],zoom:7}));const code=readFileSync(new URL('../../review/noaa-sst-pilot/scaleReview.mjs',import.meta.url),'utf8');assert.ok(code.includes('scales=candidateScales(field)'));assert.ok(!code.includes('searchParams'));});
test('old control colors are preserved for all retained values',()=>{for(const v of field.grid.values){if(v!==null)assert.deepEqual(scaleColor(v,scales[0]),sstColor(v).match(/\d+/g).map(Number));}});
test('missing and numeric zero distinct',()=>{assert.equal(scaleColor(null,scales[2]),null);assert.deepEqual(scaleColor(0,scales[2]),[53,75,112]);});
test('changed domain or policy changes tile identity',()=>{const args=[field.deliveryId,5,8,13],p=scalePolicy(scales[2]);const id=tileIdentity(...args,p);assert.equal(id,tileIdentity(...args,p));assert.notEqual(id,tileIdentity(...args,{...p,displayDomainK:[p.displayDomainK[0]-.1,p.displayDomainK[1]]}));assert.notEqual(id,tileIdentity(...args,{...p,displayDomainPolicy:'other'}));});
test('identity separates all four scale candidates',()=>assert.equal(new Set(scales.map(s=>tileIdentity(field.deliveryId,5,8,13,scalePolicy(s)))).size,4));
test('clipped inspection retains exact Kelvin/Fahrenheit',()=>{const i=field.grid.values.findIndex(x=>x!==null&&x>scales[3].domainK[1]);const v=field.grid.values[i];assert.deepEqual(scaleColor(v,scales[3]),[228,205,146]);assert.deepEqual(inspectCell(field,i),{K:v,F:fahrenheit(v),missing:null});});
test('land inspection remains land',()=>{const i=field.grid.missing.indexOf('land');assert.deepEqual(inspectCell(field,i),{K:null,F:null,missing:'land'});});
test('provider-no-data inspection stays missing',()=>{const mock={grid:{values:[null,0],missing:['provider-no-data',null]}};assert.deepEqual(inspectCell(mock,0),{K:null,F:null,missing:'provider-no-data'});assert.equal(inspectCell(mock,1).K,0);});
test('immutable presentation metadata',()=>{assert.throws(()=>scales[2].domainK.push(1));assert.throws(()=>{stats.statistics.mean.K=0;});});
test('source-mask alpha unchanged for each candidate',()=>{for(const s of scales){const tile=scaleTile(field,s,5,8,13);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=sourceIndex(field,...lonLat(5,8,13,x+.5,y+.5));assert.equal(tile.rgba[(y*256+x)*4+3],i<0||field.grid.missing[i]!==null?0:255);}}});
test('mismatched derivative rejected',()=>assert.throws(()=>scaleTile(field,{...scales[2],completeDerivativeId:'other'},5,8,13)));
test('scientific payload not mutated',()=>{assert.equal(JSON.stringify(field),before);assert.equal(createHash('sha256').update(JSON.stringify(field)).digest('hex'),createHash('sha256').update(before).digest('hex'));});
test('no viewport callback or downstream-science imports',()=>{const html=readFileSync(new URL('../../review/noaa-sst-pilot/scale.html',import.meta.url),'utf8');assert.ok(!/map\.on\(['"](?:move|zoom)/.test(html));const code=readFileSync(new URL('../../review/noaa-sst-pilot/scales.mjs',import.meta.url),'utf8');assert.ok(!/fetch\(|https?:\/\//.test(code));});
console.log(`${count} passed — display scales only; no acquisition`);
