import test from 'node:test';
import assert from 'node:assert/strict';
import {cycleV1,cycleV2,publicationV1,publicationV2,validatePublicationV1,validatePublicationV2,
  freezeEvidenceV1,assessmentContextV2,hash,ASSESSMENT_POLICY_V1} from '../../shared/oceanPublication.mjs';
import {runPublicationCycleV2,writePublicationV2,readLatestPublicationV2,pointerKeyV1,pointerKeyV2} from '../oceanState/publicationWorker.mjs';
const clone=structuredClone;
const ref=id=>({kind:'captured',referenceId:id,contractVersion:'synthetic-test-v1',sha256:hash(id)});
const scheduled='2026-09-24T12:00:00.000Z';
const evaluator='synthetic-test-explicit-assessment-v1';
function cycleInput(at=scheduled){return {scheduledAt:at,region:{id:'test-region',version:'1'},configuration:{id:'test-analysis',version:'2',governanceReference:'test-only',evaluatorVersion:evaluator,candidateUniverseVersion:'1',species:['blue-marlin'],families:['SST'],candidateUniverse:{reference:ref('universe'),candidateIds:['a','b']}}};}
function entries(c){return [{family:'SST',status:'UNAVAILABLE',reason:'test-unavailable',reference:null,product:null,representedAt:null,support:{kind:'unknown',start:null,end:null},qualification:{status:'UNKNOWN',policyReference:'test-only'},admissibility:{status:'UNASSESSED',policyReference:'test-only'},assessedAt:c.scheduledAt,ageHours:null,qualityReferences:[],lineageReferences:[]}];}
function input(version=2){
  const cycle=(version===2?cycleV2:cycleV1)(cycleInput()),evidence=freezeEvidenceV1(cycle,entries(cycle));
  return {cycle,evidence,attempt:{id:'first',startedAt:'2026-09-24T12:07:00Z',endedAt:'2026-09-24T12:09:00Z'},evaluation:{evaluatorVersion:evaluator,evidenceSetId:evidence.evidenceSetId,...(version===2?{assessmentAt:scheduled}:{}),candidateResults:cycle.configuration.candidateUniverse.candidateIds.map(candidateId=>({candidateId,species:'blue-marlin',evaluationReference:ref(candidateId),gate:{contractVersion:'pelora-unified-opportunity-ranking-input-v1',eligibleForRanking:false,reasons:['insufficient-evidence']},opportunityId:null,continuityReference:null,usedFamilies:[]})),signalReferences:[],lineageReferences:[]}};
}
function fixture(){
 const records=new Map(),claims=new Set();let pointer=null,version=0;
 const calls={evaluate:0,write:0,cas:0,seen:[]};
 const port={
  readExact:async id=>records.has(id)?{status:'FOUND',durable:true,record:clone(records.get(id))}:{status:'NOT_FOUND'},
  createIfAbsent:async(id,p)=>{calls.write++;const exists=records.has(id);if(!exists)records.set(id,clone(p));return {status:exists?'EXISTS':'CREATED',durable:true,record:clone(records.get(id))};},
  readLatest:async key=>clone(pointer??{key,version:'v0',target:null}),
  compareAndSet:async({key,expected,target})=>{calls.cas++;const actual=await port.readLatest(key);if(JSON.stringify(expected)!==JSON.stringify(actual))return {status:'CONFLICT',durable:true,snapshot:actual};pointer={key,version:`v${++version}`,target:clone(target)};return {status:'ADVANCED',durable:true,snapshot:clone(pointer)};},
  claim:async r=>{const held=claims.has(r.cycleId);claims.add(r.cycleId);return {...r,status:held?'HELD':'ACQUIRED'};},
  collectEvidence:async c=>entries(c),verifyEvidence:async e=>({status:'VERIFIED',evidenceSetId:e.evidenceSetId}),
  evaluate:async ({cycle,evidence,assessment})=>{
   calls.evaluate++;assert(Object.isFrozen(assessment));assert.equal(assessment.contractVersion,ASSESSMENT_POLICY_V1);
   const results=cycle.configuration.candidateUniverse.candidateIds.map(candidateId=>{
    calls.seen.push(assessment.assessmentAt);
    return {candidateId,species:'blue-marlin',interpretation:{candidate:{id:candidateId},species:'blue-marlin',available:true,speciesOpportunity:{available:true,score:999,eligibility:{eligibleForRanking:false}}},evaluationReference:ref(candidateId),opportunityId:null,continuityReference:null,usedFamilies:[]};
   });
   return {evaluatorVersion:cycle.configuration.evaluatorVersion,evidenceSetId:evidence.evidenceSetId,assessmentAt:assessment.assessmentAt,results,signalReferences:[],lineageReferences:[]};
  },finishedAt:async()=> '2026-09-24T12:09:00Z'
 };
 const request={cycle:cycleInput(),attemptId:'first',startedAt:'2026-09-24T12:07:00Z',assessedAt:'2026-09-24T12:10:00Z'};
 return {port,request,records,calls,run:()=>runPublicationCycleV2(request,port)};
}


import {cycleV3,publicationV3,validatePublicationV3,freezeScientificHistoryV1,SCIENTIFIC_HISTORY_V1} from '../../shared/oceanPublication.mjs';
import {runPublicationCycleV3,readLatestPublicationV3,pointerKeyV3} from '../oceanState/publicationWorker.mjs';
const historyRaw=()=>({contractVersion:SCIENTIFIC_HISTORY_V1,state:'AVAILABLE',asOf:scheduled,reason:'resolved',sourceReference:ref('qualified-source'),entries:[]});
const entry=(candidateId='a',time='2026-09-23T12:00:00Z')=>({candidateId,species:'blue-marlin',representedAt:time,evaluatedAt:time,evaluationReference:ref(hash(candidateId+time)),opportunityId:null,continuityReference:ref('continuity')});
const config3=()=>({...cycleInput(),configuration:{...cycleInput().configuration,evaluatorVersion:'synthetic-explicit-assessment-history-v1'}});
function input3(raw=historyRaw()){const p=input();p.cycle=cycleV3(config3());p.history=freezeScientificHistoryV1(p.cycle,raw);p.evaluation.evaluatorVersion=p.cycle.configuration.evaluatorVersion;p.evaluation.historyId=p.history.historyId;p.evaluation.historyState=p.history.state;return p;}
function fixture3(){const f=fixture();f.request.cycle=config3();f.raw=historyRaw();f.port.collectScientificHistory=async()=>f.raw;f.port.verifyScientificHistory=async h=>({status:'VERIFIED',historyId:h.historyId,historyState:h.state});const old=f.port.evaluate;f.port.evaluate=async args=>{assert(Object.isFrozen(args.history)&&Object.isFrozen(args.history.entries));return {...await old(args),historyId:args.history.historyId,historyState:args.history.state};};f.run=()=>runPublicationCycleV3(f.request,f.port);return f;}
test('v3 valid empty available and unavailable remain distinct',()=>{const a=publicationV3(input3());const raw=historyRaw();raw.state='UNAVAILABLE';raw.reason='source-unavailable';raw.sourceReference=null;const b=publicationV3(input3(raw));assert.notEqual(a.contentDigest,b.contentDigest);assert.deepEqual(validatePublicationV3(a),a);});
test('valid chronological entries canonicalize, detach and preserve references',()=>{const raw=historyRaw();raw.entries=[entry('b'),entry('a')];const a=input3(raw);raw.entries.reverse();assert.deepEqual(a.history,input3(raw).history);raw.entries[0].candidateId='changed';assert.equal(a.history.entries[0].candidateId,'a');assert(Object.isFrozen(a.history.entries[0].continuityReference));});
for(const [name,mutate] of Object.entries({missing:h=>delete h.asOf,contract:h=>h.contractVersion='wrong',cutoff:h=>h.asOf='2026-09-25T12:00:00Z',future:h=>h.entries=[entry('a','2026-09-25T12:00:00Z')],species:h=>{h.entries=[entry()];h.entries[0].species='wahoo';},unknown:h=>h.entries=[entry('unknown')],malformed:h=>h.entries=[entry('bad space')],duplicate:h=>h.entries=[entry(),entry()],unavailableEntries:h=>{h.state='UNAVAILABLE';h.entries=[entry()];}}))test('history rejects '+name,()=>{const raw=historyRaw();mutate(raw);assert.throws(()=>input3(raw));});
for(const key of ['user_id','captain_id','email','boat','origin','range','Fishing Log','catch','lure','bait','privateCoordinates','token','session','mission'])test('private field rejected '+key,()=>{for(const location of ['context','entry']){const raw=historyRaw();if(location==='entry'){raw.entries=[entry()];raw.entries[0][key]='private';}else raw[key]='private';assert.throws(()=>input3(raw));}});
test('invalid state is representable but cannot complete or advance',async()=>{const raw=historyRaw();raw.state='INVALID';assert.equal(input3(raw).history.state,'INVALID');assert.throws(()=>publicationV3(input3(raw)));const f=fixture3();f.raw=raw;assert.equal((await f.run()).status,'INVALID_SCIENTIFIC_HISTORY');assert.equal(f.calls.evaluate,0);assert.equal(f.calls.cas,0);});
test('missing publication history rejected',()=>{const p=input3();delete p.history;assert.throws(()=>publicationV3(p));});
test('all version namespaces are separate and cross-validation rejects',()=>{const values=[publicationV1(input(1)),publicationV2(input()),publicationV3(input3())],validators=[validatePublicationV1,validatePublicationV2,validatePublicationV3];for(let i=0;i<3;i++)for(let j=0;j<3;j++)if(i!==j)assert.throws(()=>validators[i](values[j]));assert.equal(new Set(values.map(p=>p.publicationId)).size,3);assert.equal(new Set([pointerKeyV1(values[0].cycle),pointerKeyV2(values[1].cycle),pointerKeyV3(values[2].cycle)]).size,3);});
test('worker propagates, durable reads, retries and changed-history conflicts',async()=>{const f=fixture3();const a=await f.run();assert.equal(a.status,'COMPLETED');assert.equal((await f.run()).status,'POINTER_ALREADY_CURRENT');assert.equal(f.calls.evaluate,1);const read=await readLatestPublicationV3(f.port,f.request.cycle,'2026-09-27T12:00:00Z');assert.deepEqual(read.publication.history,a.publication.history);f.raw.entries.push(entry());assert.equal((await f.run()).status,'SAME_CYCLE_HISTORY_CONFLICT');assert.deepEqual((await readLatestPublicationV3(f.port,f.request.cycle,'2026-09-27T12:00:00Z')).publication,a.publication);});
for(const field of ['historyId','historyState'])test('wrong evaluator acknowledgement '+field,async()=>{const f=fixture3(),original=f.port.evaluate;f.port.evaluate=async args=>({...await original(args),[field]:'wrong'});assert.equal((await f.run()).status,'CYCLE_FAILED');assert.equal(f.calls.write,0);});
test('corrupt durable history blocks pointer',async()=>{const f=fixture3(),original=f.port.readExact;f.port.readExact=async id=>{const r=await original(id);if(r.record)r.record.history.asOf='2099-01-01T00:00:00Z';return r;};assert.equal((await f.run()).status,'CYCLE_FAILED');assert.equal(f.calls.cas,0);});
test('execution time changes neither history nor scientific content',()=>{const p=input3(),a=publicationV3(p);p.attempt.startedAt='2026-09-27T12:00:00Z';p.attempt.endedAt='2026-09-27T12:09:00Z';const b=publicationV3(p);assert.equal(a.contentDigest,b.contentDigest);assert.deepEqual(a.history,b.history);});
test('legacy evaluator cannot claim history-aware capability',()=>{assert.throws(()=>cycleV3(cycleInput()));});

test('checkpoint v1 complete record golden unchanged',()=>assert.equal(hash(publicationV1(input(1))),'19487e7f797edc8d0ca11334c51add14eea447916f13b5cd4c63132631fa753a'));

test('checkpoint v2 complete record golden unchanged',()=>assert.equal(hash(publicationV2(input(2))),'44de65232c234157b4f3f45ac25370a7643121d8e8484b4993d03873d227d530'));

test('history accessor rejected without invocation',()=>{const raw=historyRaw();let hit=false;Object.defineProperty(raw,'asOf',{enumerable:true,get(){hit=true;return scheduled;}});assert.throws(()=>input3(raw));assert.equal(hit,false);});
test('verification acknowledgement mismatch prevents evaluation',async()=>{const f=fixture3();f.port.verifyScientificHistory=async h=>({status:'VERIFIED',historyId:h.historyId,historyState:'wrong'});assert.equal((await f.run()).status,'CYCLE_FAILED');assert.equal(f.calls.evaluate,0);});
test('external source mutation during evaluation cannot alter frozen history',async()=>{const f=fixture3(),original=f.port.evaluate;f.raw.entries=[entry()];f.port.evaluate=async args=>{f.raw.entries[0].candidateId='external-change';assert.equal(args.history.entries[0].candidateId,'a');return original(args);};const r=await f.run();assert.equal(r.status,'COMPLETED');assert.equal(r.publication.history.entries[0].candidateId,'a');});
test('unavailable history is acknowledged explicitly by evaluator',async()=>{const f=fixture3();f.raw.state='UNAVAILABLE';f.raw.sourceReference=null;const r=await f.run();assert.equal(r.status,'COMPLETED');assert.equal(r.publication.evaluation.historyState,'UNAVAILABLE');});

test('checkpoint v1 serialized bytes unchanged',()=>assert.equal(hash(JSON.stringify(publicationV1(input(1)))),'fdd0f1afa5434b20f343fdfd7fe2f56c8d06265663f5e717bbafbacfba556282'));

test('checkpoint v2 serialized bytes unchanged',()=>assert.equal(hash(JSON.stringify(publicationV2(input(2)))),'5dd760a8930e8f781c18f75e03ea22b3d5b96df027849bcaa42c4bdfdff1c409'));

// Task 12A.2 adversarial regressions; no live sources.
for(const [name,change] of Object.entries({noState:h=>delete h.state,unknownState:h=>h.state='EMPTY',noEntries:h=>delete h.entries,nullEntries:h=>h.entries=null,wrongEntry:h=>h.entries=[null],unknownField:h=>h.extra={},inherited:h=>Object.setPrototypeOf(h,{state:'AVAILABLE'}),oversized:h=>h.reason='x'.repeat(201),badReference:h=>h.sourceReference.sha256='wrong'}))test('hostile history schema '+name,()=>{const h=historyRaw();change(h);assert.throws(()=>input3(h));});
for(const time of ['2026-09-24T12:00:00.001Z','2026-09-24T12:00:01Z','2026-09-24T12:00:00.0001Z','2026-09-24T12:00:00+00:00','2026-09-24 12:00:00','invalid'])test('hostile cutoff timestamp '+time,()=>{const h=historyRaw();h.entries=[entry('a',time)];assert.throws(()=>input3(h));});
test('exact cutoff and one millisecond before are valid',()=>{for(const time of [scheduled,'2026-09-24T11:59:59.999Z']){const h=historyRaw();h.entries=[entry('a',time)];assert.doesNotThrow(()=>publicationV3(input3(h)));}});
test('duplicate semantic identities reject despite reordered keys or conflicting content',()=>{for(const conflict of [false,true]){const h=historyRaw(),a=entry(),b=Object.fromEntries(Object.entries(a).reverse());if(conflict)b.opportunityId='other';h.entries=[a,b];assert.throws(()=>input3(h));}});
for(const key of ['userId','captainId','boat_name','captain coordinates','fishing_log','Auth UUID','private trip coordinates','mission context'])test('nested private reference field '+key,()=>{const h=historyRaw();h.entries=[entry()];h.entries[0].continuityReference[key]='private';assert.throws(()=>input3(h));});
for(const value of ['', 'legacy','test-explicit-assessment-v1','test-explicit-assessment-history-v1-extra','test-explicit-assessment-history-v'])test('deceptive evaluator '+value,()=>{const c=config3();c.configuration.evaluatorVersion=value;assert.throws(()=>cycleV3(c));});
for(const [name,change] of Object.entries({missing:r=>delete r.historyId,extra:r=>r.history={entries:[]},cutoff:r=>r.asOf=scheduled,inherited:r=>Object.setPrototypeOf(r,{historyId:r.historyId}),accessor:r=>Object.defineProperty(r,'historyId',{enumerable:true,get(){throw Error('getter invoked');}})}))test('hostile evaluator acknowledgement '+name,async()=>{const f=fixture3(),original=f.port.evaluate;let invoked=false;f.port.evaluate=async a=>{const r=await original(a);change(r);if(name==='accessor')Object.defineProperty(r,'historyId',{enumerable:true,get(){invoked=true;return a.history.historyId;}});return r;};assert.equal((await f.run()).status,'CYCLE_FAILED');assert.equal(invoked,false);assert.equal(f.calls.write,0);});
for(const [name,change] of Object.entries({missing:p=>delete p.history,state:p=>p.history.state='UNAVAILABLE',cutoff:p=>p.history.asOf='2099-01-01T00:00:00Z',digest:p=>p.history.contentDigest='a'.repeat(64),entry:p=>p.history.entries[0].candidateId='b',order:p=>p.history.entries.reverse(),v2:p=>Object.assign(p,publicationV2(input()))}))test('hostile durable history '+name,async()=>{const f=fixture3();f.raw.entries=[entry('a'),entry('b')];const read=f.port.readExact;f.port.readExact=async id=>{const r=await read(id);if(r.record)change(r.record);return r;};assert.equal((await f.run()).status,'CYCLE_FAILED');assert.equal(f.calls.cas,0);});
test('invalid next cycle retains verified previous publication and increasing age',async()=>{const f=fixture3();const a=await f.run();assert.equal(a.status,'COMPLETED');f.request.cycle.scheduledAt='2026-09-24T16:00:00Z';f.request.startedAt='2026-09-24T16:07:00Z';f.request.assessedAt='2026-09-24T16:10:00Z';f.raw.asOf='2026-09-24T16:00:00Z';f.raw.state='INVALID';const r=await f.run();assert.equal(r.status,'INVALID_SCIENTIFIC_HISTORY');assert.deepEqual(r.previous.publication,a.publication);assert(r.previous.ageHours>4);assert.equal(f.calls.cas,1);});
test('meaningful history changes alter identity, key ordering does not',()=>{const h=historyRaw();h.entries=[entry()];const original=input3(h).history;for(const change of [v=>v.entries.push(entry('b')),v=>v.entries=[],v=>v.entries[0].candidateId='b',v=>v.entries[0].representedAt='2026-09-22T12:00:00Z',v=>v.entries[0].continuityReference=ref('changed')]){const v=clone(h);change(v);assert.notEqual(input3(v).history.historyId,original.historyId);}const reordered=Object.fromEntries(Object.entries(h).reverse());assert.equal(input3(reordered).history.historyId,original.historyId);});
test('latest read rejects post-acceptance history corruption and v2 pointer',async()=>{const f=fixture3();const r=await f.run();f.records.get(r.publication.publicationId).history.entries.push(entry());await assert.rejects(readLatestPublicationV3(f.port,f.request.cycle,'2026-09-27T12:00:00Z'));const old=fixture();assert.equal((await old.run()).status,'COMPLETED');await assert.rejects(readLatestPublicationV3(old.port,config3(),'2026-09-27T12:00:00Z'));});
