import {fork} from 'node:child_process';import {fileURLToPath} from 'node:url';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import fs from 'node:fs';
import {database,setup,runtime,stage,configuration} from './fixtures/localPublicationFixture.mjs';
import {createLocalFourHourPublisher} from '../durableObserve/localPublicationPublisher.mjs';
import {createPublisherLedger,registerLocalPublisherConfiguration,disableLocalPublisherConfiguration,validatePublisherConfiguration,collectRetainedCycleInput,createRetainedCurrentsEvaluator} from '../durableObserve/publicationScheduler.mjs';
import {serializeRankedPublication,readRankedPublication,createRankedPublicationComposer,byteHash} from '../durableObserve/publicationEnvelope.mjs';
import {createPublicationStore} from '../durableObserve/publicationStore.mjs';import {postgresTransaction} from '../durableObserve/postgresPorts.mjs';
import {createOceanStateReader} from '../durableObserve/oceanStateReader.mjs';import {cycleV2} from '../../shared/oceanPublication.mjs';import {verifyWorkerPrivileges} from '../durableObserve/privilegeManifest.mjs';
const limits={maxCyclesPerTick:2,maxConfigurationScan:2};
test('CP-09 isolated PostgreSQL persistent publisher mechanics',{skip:process.env.PELORA_CP09_LOCAL!=='1'},async t=>{
 const db=await database(),store=createPublicationStore({query:db.query,transaction:postgresTransaction(db.pool)});const publisher=(h,r=runtime(h))=>createLocalFourHourPublisher({enabled:true,createRuntime:async()=>r,limits});
 try{
  await t.test('restart enumeration is idempotent and deterministic existing cycle identity is retained',async()=>{const h=await setup(db);const before=await h.ledger.pending(h.c);await h.ledger.enumerate(h.c,h.now);assert.deepEqual(await createPublisherLedger({query:db.query}).pending(h.c),before);const s=await h.ledger.inspect(h.id);assert.equal(s.job.cycle_id,cycleV2(h.input.cycle).cycleId);});
  await t.test('bounded catch-up enumerates oldest missed cycles without skipping or retroactive activation',async()=>{const at=new Date(Date.now()-48*3600000);at.setUTCHours(0,0,0,0);const h=await setup(db,undefined,{at:at.toISOString(),settings:{catchUpCycles:2}});assert.equal((await h.ledger.pending(h.c)).length,2);await h.ledger.enumerate(h.c,h.now);const ids=await h.ledger.pending(h.c);assert.equal(ids.length,4);const times=await Promise.all(ids.map(async id=>(await h.ledger.inspect(id)).job.cycle_at));assert.equal(Date.parse(times[3])-Date.parse(times[0]),12*3600000);await assert.rejects(h.ledger.enumerate(h.c,new Date(Date.parse(h.c.approvedAt)-1).toISOString()));});
  await t.test('approval/configuration is server-only; other species, private context and missing bounds reject',async()=>{const h=configuration();for(const change of [x=>x.context.species='yellowfin',x=>delete x.settings.maxAttempts,x=>x.context.captainId='private']){const bad=structuredClone(h.c);change(bad);assert.throws(()=>validatePublisherConfiguration(bad));}await assert.rejects(h.ledger?.call?.('enumerate','unregistered')??db.query("SELECT cp09.worker('enumerate','unregistered',NULL,NULL)"));});
  await t.test('available, real controlled upstream zero, partial positive/zero, unavailable and empty cohort preserved',async()=>{for(const [states,state] of [[[{adequate:true,positive:true}],'available'],[[{adequate:true,positive:false}],'governed-zero'],[[{adequate:true,positive:true},'failed'],'partial'],[[{adequate:true,positive:false},'failed'],'partial'],[[{adequate:false,positive:false}],'unavailable'],[[],'unavailable']]){const h=await setup(db,states),p=publisher(h);const r=await p.tick();assert.equal(r.results[0].status,'COMMITTED');const s=await h.ledger.inspect(h.id);assert.equal(readRankedPublication(s.submissionText).producerBundle.evaluationState.state,state);assert.equal((await store.read({context:h.c.context,mode:'current-cycle'})).scientificState,state);await p.close();}});
  await t.test('zero users and zero provider requests; bounded transactions outside collect/evaluate',async()=>{const h=await setup(db);let calls=0;const savedFetch=globalThis.fetch;globalThis.fetch=()=>{calls++;throw Error('provider-work-forbidden');};const r=runtime(h,{collect:async()=>{assert.equal((await db.owner.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE usename='pelora_cp02_worker' AND state='idle in transaction'")).rows[0].n,0);return h.input;}}),p=publisher(h,r);try{assert.equal((await p.tick()).results[0].status,'COMMITTED');assert.equal(calls,0);}finally{globalThis.fetch=savedFetch;await p.close();}});
  await t.test('two competing publishers produce one accepted version',async()=>{const h=await setup(db),a=publisher(h),b=publisher(h);const r=await Promise.all([a.tick(),b.tick()]);assert.equal(r.flatMap(x=>x.results).filter(x=>x.status==='COMMITTED').length,1);assert((await h.ledger.inspect(h.id)).completion);await a.close();await b.close();});
  await t.test('obsolete attempt cannot freeze, prepare, finalize or bypass managed CP-08 after reclaim',async()=>{const h=await setup(db,undefined,{settings:{leaseMs:1000,executionTimeoutMs:800}}),s=await stage(h);await db.owner.query('SELECT pg_sleep(1.1)');const cap=randomUUID(),claim=await h.ledger.claim(h.id,cap);assert.equal(claim.status,'OWNED');assert.equal(claim.fence,s.claim.fence+1);await assert.rejects(h.ledger.finalize(h.id,h.cap,s.claim.fence),/publisher-not-owned/);await assert.rejects(store.submit(s.p),/managed-cycle/);await h.ledger.finalize(h.id,cap,claim.fence);assert.equal((await h.ledger.inspect(h.id)).submissionText,serializeRankedPublication(s.p));});
  await t.test('freeze conflicts and later evidence cannot replace immutable cycle inputs',async()=>{const h=await setup(db),s=await stage(h),before=await h.ledger.inspect(h.id);await assert.rejects(h.ledger.freeze(h.id,h.cap,s.claim.fence,{...s.freeze,constructedAt:new Date().toISOString()}),/freeze-conflict/);await h.ledger.release(h.id,h.cap);let collected=0;const p=publisher(h,runtime(h,{collect:async()=>{collected++;throw Error('later-evidence-must-not-be-read');}}));assert.equal((await p.tick()).results[0].status,'COMMITTED');assert.equal(collected,0);assert.equal((await h.ledger.inspect(h.id)).freezeText,before.freezeText);await p.close();});
  await t.test('crash before/after freeze, evaluation and prepare recovers exact persisted inputs/bytes',async()=>{for(const stop of ['before-freeze','after-freeze','evaluate','after-prepare']){const h=await setup(db);let fail=true;const base=runtime(h),ledger={...h.ledger,configurations:async()=>[h.c],freeze:async(...args)=>{if(fail&&stop==='before-freeze')throw Error('crash');const v=await h.ledger.freeze(...args);if(fail&&stop==='after-freeze')throw Error('crash');return v;},prepare:async(...args)=>{const v=await h.ledger.prepare(...args);if(fail&&stop==='after-prepare')throw Error('crash');return v;}},r={...base,ledger,compose:async(...args)=>{if(fail&&stop==='evaluate')throw Error('crash');return base.compose(...args);}},p=publisher(h,r);assert.equal((await p.tick()).results[0].status,'RECOVERABLE');const prior=await h.ledger.inspect(h.id);fail=false;assert.equal((await p.tick()).results[0].status,'COMMITTED');const after=await h.ledger.inspect(h.id);if(prior.freezeText)assert.equal(after.freezeText,prior.freezeText);if(prior.submissionText)assert.equal(after.submissionText,prior.submissionText);await p.close();}});
  await t.test('lost committed acknowledgement reconciles first without another submission/revision',async()=>{const h=await setup(db);let finalized=0;const ledger={...h.ledger,finalize:async(...args)=>{finalized++;await h.ledger.finalize(...args);throw Error('lost-ack');}},p=publisher(h,runtime(h,{ledger}));assert.equal((await p.tick()).results[0].status,'RECONCILED');assert.equal(finalized,1);assert.equal((await h.ledger.inspect(h.id)).job.state,'completed');await p.tick();assert.equal(finalized,1);await p.close();});
  await t.test('transaction rollback rolls publication and terminal completion back together',async()=>{const h=await setup(db),s=await stage(h),client=await db.pool.connect();try{await client.query('BEGIN');await client.query('SET CONSTRAINTS ALL IMMEDIATE');await client.query('SELECT cp09.worker($1,$2,$3,$4)',['finalize',h.id,h.cap,JSON.stringify({fence:s.claim.fence})]);await client.query('ROLLBACK');}finally{client.release();}assert.equal((await h.ledger.inspect(h.id)).completion,null);assert.equal((await store.read({context:h.c.context,mode:'current-cycle'})).record,null);await h.ledger.finalize(h.id,h.cap,s.claim.fence);});
  await t.test('disable revokes in-progress ownership; no newly disabled work is generated',async()=>{const h=await setup(db),s=await stage(h);await disableLocalPublisherConfiguration(db.owner,h.c.id,new Date().toISOString());assert.equal((await h.ledger.finalize(h.id,h.cap,s.claim.fence)).state,'disabled');assert.equal((await store.read({context:h.c.context,mode:'current-cycle'})).record,null);assert.deepEqual(await h.ledger.enumerate(h.c,h.now),[]);});
  await t.test('deadline creates truthful delayed publication; exhausted retries persist failure without zero',async()=>{const h=await setup(db,undefined,{settings:{deadlineMs:1}}),p=publisher(h);assert.equal((await p.tick()).results[0].status,'COMMITTED');const state=await store.read({context:h.c.context,mode:'current-cycle'});assert.equal(state.lifecycle,'delayed');assert.equal(state.scientificState,null);await p.close();const failed=await setup(db,undefined,{settings:{maxAttempts:1}});await failed.ledger.claim(failed.id,failed.cap);await failed.ledger.release(failed.id,failed.cap);assert.equal((await failed.ledger.claim(failed.id,randomUUID())).status,'RETRY_EXHAUSTED');assert.equal((await failed.ledger.inspect(failed.id)).job.state,'failed');});
  await t.test('explicit correction/withdrawal lineage survives ordinary scheduler replay',async()=>{const h=await setup(db),p=publisher(h);await p.tick();const s=await h.ledger.inspect(h.id),original=readRankedPublication(s.submissionText);const {envelope}=await import('./fixtures/rankedPublicationFixture.mjs');const corrected=await envelope({...h.input,revision:2,parentId:original.versionId,action:'CORRECTION',reason:'explicit-governed-correction'});await db.owner.query('SELECT cp08.submit_internal($1)',[serializeRankedPublication(corrected)]);const withdrawn=await envelope({...h.input,revision:3,parentId:corrected.versionId,action:'WITHDRAWAL',lifecycle:'withdrawn',reason:'explicit-governed-withdrawal'});await db.owner.query('SELECT cp08.submit_internal($1)',[serializeRankedPublication(withdrawn)]);await p.tick();const state=await store.read({context:h.c.context,mode:'current-cycle'});assert.equal(state.lifecycle,'withdrawn');assert.equal(state.activePublication,null);await p.close();});
  await t.test('shutdown interrupts cooperative collect; timer cleans up and no work continues',async()=>{const h=await setup(db);let closeCalls=0,started;const began=new Promise(r=>started=r),p=publisher(h,runtime(h,{collect:async(c,at,{signal})=>{started();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('abort')),{once:true}));return h.input;},close:async()=>closeCalls++}));const tick=p.tick();await began;await p.close();assert.equal((await tick).results[0].status,'RECOVERABLE');assert.equal(closeCalls,1);assert.equal((await p.tick()).status,'CLOSED');});

  async function child(h,mode){const p=fork(fileURLToPath(new URL('./fixtures/localPublisherCrashChild.mjs',import.meta.url)),[],{stdio:['ignore','ignore','ignore','ipc'],windowsHide:true});const message=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{p.kill();reject(Error('child-timeout'));},10000);p.once('message',m=>{clearTimeout(timeout);resolve(m);});p.once('exit',code=>{clearTimeout(timeout);if(code)reject(Error('child-failed'));});p.send({id:h.id,config:h.c,input:h.input,mode});});return {process:p,message,kill:async()=>{if(p.exitCode!==null)return;const exit=new Promise(resolve=>p.once('exit',resolve));p.kill();await exit;}};}
  await t.test('two actual publisher processes compete without duplicate completion',async()=>{const h=await setup(db),both=await Promise.all([child(h,'tick'),child(h,'tick')]);assert.equal(both.flatMap(x=>x.message.result.results).filter(x=>x.status==='COMMITTED').length,1);assert((await h.ledger.inspect(h.id)).completion);for(const x of both)await x.kill();});
  await t.test('actual process interruption across freeze/evaluate/prepare/finalize windows',async()=>{for(const mode of ['before-freeze','after-freeze','after-evaluate','after-prepare','inside-finalize','after-finalize']){const h=await setup(db,undefined,{settings:{leaseMs:1000,executionTimeoutMs:800}}),x=await child(h,mode);await x.kill();const before=await h.ledger.inspect(h.id);if(mode!=='after-finalize')assert.equal(before.completion,null);else assert(before.completion);await db.owner.query('SELECT pg_sleep(1.1)');const p=publisher(h);await p.tick();const after=await h.ledger.inspect(h.id);assert(after.completion);if(before.freezeText)assert.equal(after.freezeText,before.freezeText);if(before.submissionText)assert.equal(after.submissionText,before.submissionText);await p.close();}});
  await t.test('lease expires while waiting for publication context lock: transition rejects',async()=>{const h=await setup(db,undefined,{settings:{leaseMs:1000,executionTimeoutMs:800}}),s=await stage(h);await db.owner.query('BEGIN');await db.owner.query('SELECT 1 FROM cp08.contexts WHERE context_key=$1 FOR UPDATE',[s.p.contextKey]);const pending=h.ledger.finalize(h.id,h.cap,s.claim.fence).then(()=>({accepted:true}),error=>({error}));await db.owner.query('SELECT pg_sleep(1.1)');await db.owner.query('COMMIT');const result=await pending;assert.match(result.error.message,/publisher-not-owned/);assert.equal((await h.ledger.inspect(h.id)).completion,null);});
  await t.test('constraint timing cannot change consumption: accepted transition survives later lease expiry',async()=>{const h=await setup(db,undefined,{settings:{leaseMs:2000,executionTimeoutMs:1000}}),s=await stage(h),client=await db.pool.connect();try{await client.query('BEGIN');await client.query('SET CONSTRAINTS ALL IMMEDIATE');await client.query('SELECT cp09.worker($1,$2,$3,$4)',['finalize',h.id,h.cap,JSON.stringify({fence:s.claim.fence})]);await client.query('SELECT pg_sleep(2.1)');await client.query('COMMIT');}finally{client.release();}assert((await h.ledger.inspect(h.id)).completion);assert.equal((await h.ledger.claim(h.id,randomUUID())).status,'TERMINAL');});
  await t.test('actual retained CP-07 collector preserves snapshot construction, unknown receipt, and incomplete science',async()=>{const at=configuration().at,row=(await db.owner.query("SELECT o.job_id FROM cp03.observations o LEFT JOIN cp06.links l USING(job_id) WHERE (o.timestamps->>'acceptedAt')::timestamptz<=$1 AND l.job_id IS NULL ORDER BY o.job_id LIMIT 1",[at])).rows[0];assert(row);const v=(await db.query('SELECT cp03.lookup($1) AS value',[row.job_id])).rows[0].value,m=v.context.manifest;const base=configuration(),ctx={...base.c.context,region:m.region},cycleConfiguration={...base.c.cycleConfiguration,families:['CURRENTS']};const h=await setup(db,undefined,{body:{context:ctx,cycleConfiguration,adapterVersion:'currents-retained-incomplete-explicit-assessment-v1',scopes:[{candidateId:'candidate-0',scope:{manifestDigest:m.digest,region:m.region,product:{family:m.product.family,provider:m.product.provider,dataset:m.product.dataset,productId:m.product.productId},cellKey:v.index.cell_key}}],requireHistoricalReceipt:true}});const clock={now:()=>new Date().toISOString()},reader=createOceanStateReader({query:db.query,clock}),input=await collectRetainedCycleInput(h.c,h.at,{reader,clock});const content=input.artifacts[0].content;assert(input.artifacts[0].receivedAt>h.at);assert.equal(content.snapshots[0].snapshot.queryContext,'historical');assert(content.snapshots[0].snapshot.observations.every(o=>o.provenance.receipt.status==='AS_OF_AUTHORITY_UNKNOWN'));
   const sourceOnly=await collectRetainedCycleInput({...h.c,requireHistoricalReceipt:false},h.at,{reader,clock}),natural=await (await createRankedPublicationComposer({evaluate:await createRetainedCurrentsEvaluator(sourceOnly.artifacts[0].reference),clock})).compose(sourceOnly);assert.equal(natural.producerBundle.evaluationState.state,'unavailable');assert.equal(natural.producerBundle.results[0].value.negativeConclusionAdequacy.adequate,false);const evaluate=await createRetainedCurrentsEvaluator(input.artifacts[0].reference),p=await (await createRankedPublicationComposer({evaluate,clock})).compose(input);assert.equal(p.producerBundle.evaluationState.state,'unavailable');assert.equal(p.producerBundle.inputsUsed[0].receivedAt,input.artifacts[0].receivedAt);const runner=publisher(h,runtime(h,{collect:async()=>input,compose:async x=>(await createRankedPublicationComposer({evaluate,clock})).compose(x)}));assert.equal((await runner.tick()).results[0].status,'COMMITTED');await runner.close();
  });
  await t.test('failed lifecycle is recorded without scientific result or history substitution',async()=>{const h=await setup(db),r=runtime(h),p=publisher(h,{...r,compose:async input=>r.compose({...input,lifecycle:'failed',reason:'controlled-evaluator-failure'})});assert.equal((await p.tick()).results[0].status,'COMMITTED');const s=await store.read({context:h.c.context,mode:'current-cycle'});assert.equal(s.lifecycle,'failed');assert.equal(s.scientificState,null);assert.equal(s.activePublication,null);await p.close();});

  await t.test('real polling timer starts explicitly and shuts down with no post-close ticks',async()=>{const h=await setup(db);let read=0,closed=0;const r=runtime(h,{close:async()=>closed++}),ledger={...r.ledger,configurations:async()=>{read++;return [h.c];}},p=publisher(h,{...r,ledger});assert.equal((await p.start()).status,'STARTED');for(let i=0;i<50;i++){if((await h.ledger.inspect(h.id)).completion)break;await new Promise(resolve=>setTimeout(resolve,10));}assert((await h.ledger.inspect(h.id)).completion);await p.close();const before=read;await new Promise(resolve=>setTimeout(resolve,1050));assert.equal(read,before);assert.equal(closed,1);});
  await t.test('database-clock configuration cannot retrospectively authorize earlier cycles',async()=>{const h=configuration(undefined,{body:{clockMode:'DATABASE',adapterVersion:'currents-retained-incomplete-explicit-assessment-v1'}});await assert.rejects(registerLocalPublisherConfiguration(db.owner,h.c));});
  await t.test('after-cutoff receipt remains unavailable historical authority in retained snapshots',async()=>{const h=configuration();const clock={now:()=>new Date().toISOString()},content={contractVersion:'pelora-retained-publication-inputs-v1',assessmentCutoff:h.at,constructedAt:clock.now(),requireHistoricalReceipt:true,snapshots:[{candidateId:'candidate-0',snapshot:{contractVersion:'pelora-ocean-state-reader-v1',status:'READ_UNAVAILABLE',observations:[]}}]};const reference={kind:'captured',contractVersion:content.contractVersion,referenceId:'late-receipt-controlled-input',sha256:byteHash(JSON.stringify(content))};const evaluate=await createRetainedCurrentsEvaluator(reference),result=await evaluate({binding:{assessmentCutoff:h.at},candidates:h.c.candidates,species:'blue-marlin'},()=>({...content,snapshots:[{candidateId:'candidate-0',snapshot:{observations:[{provenance:{receipt:{status:'NOT_RECEIVED_BY_ASSESSMENT',record:{receivedAt:new Date(Date.parse(h.at)+1).toISOString()}}}}]}}]}));assert.equal(result.results[0].status,'rejected');assert.equal(result.results[0].reason,'historical-possession-unproven');});
  await t.test('extended least-privilege manifest validates exact routines and default deny',async()=>{const m=JSON.parse(fs.readFileSync(new URL('../durableObserve/publisherPrivilegeManifest.v1.json',import.meta.url)));assert.equal((await verifyWorkerPrivileges((...args)=>db.owner.query(...args),m)).status,'PASS');});
  await t.test('worker cannot directly access ledger or privileged CP-08 internal routine',async()=>{for(const table of ['configurations','disables','jobs','attempts','freezes','submissions','completions'])for(const verb of ['SELECT * FROM','DELETE FROM','TRUNCATE'])await assert.rejects(db.query(`${verb} cp09.${table}`),e=>e.code==='42501');await assert.rejects(db.query("SELECT cp08.submit_internal('{}')"),e=>e.code==='42501');await assert.rejects(db.query('CREATE TABLE cp09.forge(x int)'),e=>e.code==='42501');await assert.rejects(db.owner.query('UPDATE cp09.freezes SET record_text=record_text'),/immutable-record/);});
 }finally{for(const id of db.registered)await disableLocalPublisherConfiguration(db.owner,id,new Date().toISOString());await db.close();}
});
