import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {exactJson} from '../exactScientificEvidence.mjs';
import {endpoints,history,run,encoded,consumers,times} from './fixtures/chlorophyllTemporalDerivedFinitenessFixture.mjs';
import {buildSeaSurfaceTemperaturePersistence,buildCurrentPersistence,buildTemporalFeatureContinuity,buildOceanPersistence,buildOceanEvolution} from '../server.js';
const baseline=JSON.parse(readFileSync(new URL('./fixtures/temporalDerivedFiniteBaseline.v1.json',import.meta.url),'utf8'));
const decode=x=>x&&typeof x==='object'?(x.signedZero==='-0'?-0:Array.isArray(x)?x.map(decode):Object.fromEntries(Object.entries(x).map(([k,v])=>[k,decode(v)]))):x;
for(const [i,c] of baseline.controls.entries())test('independent unchanged-checkpoint finite chlorophyll output '+i,()=>{assert.deepEqual(encoded(run(decode(c.points),c.kind)),c.result);});
for(const family of ['direct','gap'])for(const sign of [1,-1])test(family+' overflow '+sign+' retains sources and finite independent facts',async t=>{
 const points=await endpoints(t,family,[sign*1e308,-sign*1e308]);
 for(const kind of Object.keys(consumers)){const rows=history(points,kind),before=exactJson(rows),r=consumers[kind]({historicalSnapshots:rows});assert.equal(exactJson(rows),before);assert.equal(r.available,false);assert.equal(r.classification,'unavailable');assert.equal(r.lifecycleState,null);assert.equal(r.reason,'nonfinite-temporal-derivation');assert.equal(r.values.concentrationChangeMgM3,null);assert.equal(r.values.firstConcentrationMgM3,sign*1e308);assert.equal(r.values.lastConcentrationMgM3,-sign*1e308);assert.equal(r.values.durationHours,24);assert.equal(r.confidence.level,'Unavailable');assert.equal(r.confidence.score,0);assert.equal(buildTemporalFeatureContinuity({featurePersistence:r}).available,false);assert.doesNotThrow(()=>exactJson(r));assert.deepEqual(r,consumers[kind]({historicalSnapshots:structuredClone(rows)}));}
});
const siblingRows=(values,directions=[90,90])=>values.map((v,i)=>({snapshot:{available:true,identity:{snapshotId:'controlled-r9-'+i},metadata:{time:{observedAt:times[i]}},observation:{observations:{sst:{temperatureFahrenheit:v},currents:{speedKnots:v,directionDegrees:directions[i]}}}}}));
for(const [name,fn,key,first,last]of [['sst',buildSeaSurfaceTemperaturePersistence,'temperatureChangeFahrenheit','firstTemperatureFahrenheit','lastTemperatureFahrenheit'],['current',buildCurrentPersistence,'speedChangeKnots','firstSpeedKnots','lastSpeedKnots']]){
 for(const sign of [1,-1])test(name+' overflow '+sign+' clears dependent lifecycle/continuity',()=>{const rows=siblingRows([sign*1e308,-sign*1e308]),before=exactJson(rows),r=fn({historicalSnapshots:rows});assert.equal(exactJson(rows),before);assert.equal(r.values[key],null);assert.equal(r.values[first],sign*1e308);assert.equal(r.values[last],-sign*1e308);assert.equal(r.available,false);assert.equal(r.lifecycleState,null);assert.equal(r.confidence.score,0);assert.equal(buildTemporalFeatureContinuity({featurePersistence:r}).available,false);assert.doesNotThrow(()=>exactJson(r));});
 test(name+' signed zero endpoints and exact identity unchanged',()=>{const rows=siblingRows([-0,0]),before=exactJson(rows),r=fn({historicalSnapshots:rows});assert(Object.is(r.values[first],-0));assert(Object.is(r.values[last],0));assert.equal(exactJson(rows),before);assert.equal(r.available,true);});
 test(name+' equal extreme finite and ordinary delta unchanged',()=>{for(const [values,want]of [[[1e308,1e308],0],[[1,2],1],[[2,1],-1],[[Number.MIN_VALUE,-Number.MIN_VALUE],-2*Number.MIN_VALUE]]){const r=fn({historicalSnapshots:siblingRows(values)});assert.equal(r.available,true);assert.equal(r.values[key],want);}});
}
test('current failed speed retains independently finite direction fact without certifying full tuple',()=>{const r=buildCurrentPersistence({historicalSnapshots:siblingRows([1e308,-1e308],[90,100])});assert.equal(r.values.directionChangeDegrees,10);assert.equal(r.values.directionalStability,null);assert.equal(r.available,false);});
test('aggregate propagation is local; valid SST remains assessed, failed biological features do not',async t=>{
 const points=await endpoints(t),selections={};for(const name of ['buildPersistenceEvidence','buildSeaSurfaceTemperaturePersistence','buildCurrentPersistence','buildCurrentEdgePersistence','buildCurrentShearPersistence','buildCurrentConvergencePersistence','buildEnvironmentalTransitionPersistence','buildSurfaceWaterCharacterPersistence','buildWaterMassPersistence','buildMixingZonePersistence','buildOceanFrontPersistence','buildProductivityPersistence','buildClarityPersistence'])selections[name]={inputs:[]};
 selections.buildSeaSurfaceTemperaturePersistence.inputs=siblingRows([77,78]);selections.buildProductivityPersistence.inputs=history(points,'productivity');selections.buildClarityPersistence.inputs=history(points,'clarity');const p=buildOceanPersistence({historyBoundary:{selections}});assert.equal(p.featurePersistence.seaSurfaceTemperature.available,true);assert.equal(p.featurePersistence.seaSurfaceTemperature.values.temperatureChangeFahrenheit,1);assert.equal(p.values.assessedFeatureCount,1);assert.equal(p.continuitySummary.assessedContinuityCount,1);for(const kind of ['productivity','clarity']){assert.equal(p.featurePersistence[kind].available,false);assert.equal(p.featureContinuity[kind].available,false);}
 const e=buildOceanEvolution({oceanPersistence:p});assert.equal(e.lifecycleSummary.assessedFeatureCount,1);for(const kind of ['productivity','clarity'])assert.equal(e.featureEvolution[kind].available,false);assert.doesNotThrow(()=>exactJson(p));assert.doesNotThrow(()=>exactJson(e));
});

for(const [i,c]of baseline.siblings.entries())test('independent checkpoint sibling full output '+i,()=>{const fn=c.name==='buildCurrentPersistence'?buildCurrentPersistence:buildSeaSurfaceTemperaturePersistence;assert.deepEqual(encoded(fn({historicalSnapshots:decode(c.rows)})),c.result);});
test('pure temporal calls are clock-independent and replay identically across processes',()=>{
 const code=`import {buildSeaSurfaceTemperaturePersistence,buildCurrentPersistence} from './backend/server.js';import {exactJson} from './backend/exactScientificEvidence.mjs';globalThis.fetch=()=>{throw Error('no acquisition');};Date.now=()=>{throw Error('no implicit clock');};const rows=${JSON.stringify(siblingRows([1e308,-1e308]))};console.log(exactJson([buildSeaSurfaceTemperaturePersistence({historicalSnapshots:rows}),buildCurrentPersistence({historicalSnapshots:rows})]));`;
 const replay=()=>spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8',windowsHide:true});const a=replay(),b=replay();assert.equal(a.status,0,a.stderr);assert.equal(b.status,0,b.stderr);assert.equal(a.stdout,b.stdout);
});

test('chlorophyll literal signed-zero endpoints remain exact source facts',async t=>{const points=await endpoints(t,'direct',[.3,.4]);for(const kind of Object.keys(consumers)){const rows=history(points,kind);rows[0].snapshot.observation.evidence.groups[kind].values.concentrationMgM3=-0;rows[1].snapshot.observation.evidence.groups[kind].values.concentrationMgM3=0;const before=exactJson(rows),r=consumers[kind]({historicalSnapshots:rows});assert(Object.is(r.values.firstConcentrationMgM3,-0));assert(Object.is(r.values.lastConcentrationMgM3,0));assert.equal(exactJson(rows),before);assert.equal(r.available,true);}});
