// Targeted controlled completed/prepared publication restart; no earlier restart suite.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {database} from '../backend/tests/fixtures/localPublicationFixture.mjs';import {setupControlledP4} from '../backend/tests/fixtures/controlledRetainedPublicationFixture.mjs';import {createControlledP4Runtime} from '../backend/durableObserve/controlledRetainedPublication.mjs';
import {createLocalFourHourPublisher} from '../backend/durableObserve/localPublicationPublisher.mjs';import {createPublisherLedger,PUBLISHER_FREEZE,disableLocalPublisherConfiguration} from '../backend/durableObserve/publicationScheduler.mjs';import {createPublicationStore} from '../backend/durableObserve/publicationStore.mjs';import {cycleV2} from '../shared/oceanPublication.mjs';import {serializeRankedPublication,byteHash} from '../backend/durableObserve/publicationEnvelope.mjs';
if(process.env.PELORA_CP09_P4A_LOCAL!=='1')throw Error('controlled-restart-opt-in-required');
const root=path.join(process.env.LOCALAPPDATA,'Pelora/PostgreSQL/pelora_phase3_qualification');let db=await database(),completed,pending,publisher;
try{
 completed=await setupControlledP4(db,{count:1,native:true});pending=await setupControlledP4(db,{count:1});const ready=await completed.publisher();publisher=ready.publisher;assert.equal((await publisher.tick()).results[0].status,'COMMITTED');await publisher.close();
 const runtime=await createControlledP4Runtime({query:db.query,configuration:pending.c}),cap=randomUUID(),claim=await pending.ledger.claim(pending.id,cap),input=await runtime.collect(pending.c,pending.x.assessment.assessmentAt,{});
 await pending.ledger.freeze(pending.id,cap,claim.fence,{contractVersion:PUBLISHER_FREEZE,configurationId:pending.c.id,cycleId:cycleV2(input.cycle).cycleId,constructedAt:new Date().toISOString(),input});const p=await runtime.compose(input,pending.c);await pending.ledger.prepare(pending.id,cap,claim.fence,p);await pending.ledger.release(pending.id,cap);
 async function snapshot(){const s=(await db.owner.query("SELECT current_database() AS db,current_setting('data_directory') AS data,current_setting('listen_addresses') AS listen,inet_server_port() AS port,pg_postmaster_start_time() AS started")).rows[0];assert.equal(s.db,'pelora_phase3_qualification');assert.equal(s.listen,'127.0.0.1');assert.equal(s.port,55432);assert.equal(path.resolve(s.data).toLowerCase(),path.resolve(root,'data').toLowerCase());const ledger=createPublisherLedger({query:db.query}),a=await ledger.inspect(completed.id),b=await ledger.inspect(pending.id),read=await createPublicationStore({query:db.query}).read({context:completed.c.context,mode:'exact-cycle',scheduledAt:completed.x.assessment.assessmentAt});assert.equal(serializeRankedPublication(read.record),a.submissionText);return {started:s.started.toISOString(),completed:{jobId:completed.id,freeze:a.freezeText,submission:a.submissionText,versionId:a.completion.version_id},pending:{jobId:pending.id,freeze:b.freezeText,submission:b.submissionText}};}
 const before=await snapshot();await db.close();db=null;
 const restart=spawnSync('C:/Program Files/PostgreSQL/18/bin/pg_ctl.exe',['restart','-D',path.join(root,'data'),'-w','-t','30','-m','fast','-l',path.join(root,'cp09b-p4a-restart.log')],{encoding:'utf8',windowsHide:true,timeout:45000});assert.equal(restart.status,0,'isolated-restart-failed');db=await database();const after=await snapshot();assert.notEqual(before.started,after.started);assert.deepEqual(before.completed,after.completed);assert.deepEqual(before.pending,after.pending);
 const resumed=await createControlledP4Runtime({query:db.query,configuration:pending.c,hooks:{beforeCollect(){throw Error('no recollection');},beforeCompute(){throw Error('no reevaluation');}}});publisher=createLocalFourHourPublisher({enabled:true,createRuntime:async()=>resumed});assert.equal((await publisher.tick()).results[0].status,'COMMITTED');const final=await createPublisherLedger({query:db.query}).inspect(pending.id);assert.equal(final.freezeText,before.pending.freeze);assert.equal(final.submissionText,before.pending.submission);
 const report={contractVersion:'pelora-p4a-targeted-restart-evidence-v1',result:'PASS',beforeStarted:before.started,afterStarted:after.started,completedJobId:completed.id,preparedJobId:pending.id,completedVersionId:before.completed.versionId,recoveredVersionId:final.completion.version_id,completedFreezeDigest:byteHash(before.completed.freeze),completedSubmissionDigest:byteHash(before.completed.submission),preparedFreezeDigest:byteHash(before.pending.freeze),preparedSubmissionDigest:byteHash(before.pending.submission),configurationIds:[completed.c.id,pending.c.id],sourceReferences:JSON.parse(before.completed.freeze).input.artifacts[0].content.records.map(r=>r.reference),noRecollectionOrReevaluation:true};
 fs.mkdirSync('.local/ocean-quarantine/cp09b-p4a',{recursive:true});fs.writeFileSync('.local/ocean-quarantine/cp09b-p4a/restart.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({result:'PASS',completedJobId:completed.id,recoveredVersionId:final.completion.version_id}));
}finally{await publisher?.close();if(!db)db=await database();for(const h of [completed,pending])if(h)await disableLocalPublisherConfiguration(db.owner,h.c.id,new Date().toISOString());await db.close();}
