// Bounded R9 qualification; existing isolated profile, no restart or migration.
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
if(process.env.PELORA_R9_LOCAL!=='1')throw Error('explicit-isolated-qualification-opt-in-required');
const out=path.resolve('.local/ocean-quarantine/r9'),hash=x=>createHash('sha256').update(x).digest('hex');fs.mkdirSync(out,{recursive:true});
const files=['backend/server.js','backend/tests/chlorophyllTemporalDerivedFiniteness.test.js',"backend/tests/activeHistoricalTemporalProvenance.test.js","backend/tests/consumerAwareHistoricalSelectionPolicy.test.js","backend/tests/consumerAwareHistorySelection.test.js","backend/tests/historyAssessmentCutoff.test.js",'backend/tests/temporalDerivedFinitenessRepair.test.mjs','backend/tests/fixtures/temporalDerivedFiniteBaseline.v1.json','scripts/qualifyTemporalDerivedFiniteness.mjs'];
const fingerprints=Object.fromEntries(files.map(p=>[p,hash(fs.readFileSync(p))]));
// Preserve earlier diagnostic artifacts in place; only new scratch writes are redirected.
const preload=path.join(out,'preserveEvidence.mjs');
fs.writeFileSync(preload,"import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {syncBuiltinESMExports} from 'node:module';import cp from 'node:child_process';const spawn=cp.spawnSync.bind(cp);cp.spawnSync=(executable,args,options)=>{if(args.includes('--test')&&args.some(p=>p.endsWith('postgresRecovery.test.mjs')))args=[...args.slice(0,1),'--test-skip-pattern=^real PostgreSQL restart between empty/raw/staged interruptions preserves state and deterministic retry$',...args.slice(1)];return spawn(executable,args,options);};const write=fs.writeFileSync.bind(fs),read=fs.readFileSync.bind(fs),root=path.resolve('.local/ocean-quarantine'),out=path.resolve(root,'r9/replayed-evidence');fs.writeFileSync=(p,...args)=>{if(typeof p==='string'||p instanceof URL){const full=path.resolve(p instanceof URL?fileURLToPath(p):p);if(full.startsWith(root+path.sep)&&!full.startsWith(path.join(root,'r9')+path.sep)){const target=path.join(out,path.relative(root,full));fs.mkdirSync(path.dirname(target),{recursive:true});return write(target,...args);}}return write(p,...args);};fs.readFileSync=(p,...args)=>{if(typeof p==='string'||p instanceof URL){const full=path.resolve(p instanceof URL?fileURLToPath(p):p);if(full.startsWith(root+path.sep)&&!full.startsWith(path.join(root,'r9')+path.sep)){const target=path.join(out,path.relative(root,full));if(fs.existsSync(target))return read(target,...args);}}return read(p,...args);};syncBuiltinESMExports();\n");
const env={...process.env,NODE_OPTIONS:[process.env.NODE_OPTIONS??'',`--import=${pathToFileURL(preload).href}`].filter(Boolean).join(' '),PELORA_TEST_OCEAN_CONDITIONS:'1',PELORA_CP08_LOCAL:'1',PELORA_CP09_LOCAL:'1',PELORA_CP09B_P2_LOCAL:'1',PELORA_CP09_P4A_LOCAL:'1'};
const commands=[];
function run(name,args){const r=spawnSync(process.execPath,args,{env,encoding:'utf8',windowsHide:true,maxBuffer:32e6,timeout:900000});const log=(r.stdout??'')+'\n'+(r.stderr??'');fs.writeFileSync(path.join(out,name+'.log'),log);const count=k=>Number(log.match(new RegExp('(?:\\u2139|#)\\s+'+k+'\\s+(\\d+)'))?.[1]??0);const result={name,command:['node',...args],exit:r.status,tests:count('tests'),passed:count('pass'),failed:count('fail'),skipped:count('skipped'),cancelled:count('cancelled'),manualPassLines:(log.match(/^PASS\b/gm)??[]).length,logSha256:hash(log)};commands.push(result);fs.writeFileSync(path.join(out,'commands.json'),JSON.stringify({fingerprints,commands},null,2)+'\n');console.log(JSON.stringify(result));assert.equal(r.status,0,name+' failed; see R9 log');}
for(const p of files.filter(p=>!p.endsWith('.json')))run('syntax-'+path.basename(p),['--check',p]);
run('r9-focused',['--test','backend/tests/temporalDerivedFinitenessRepair.test.mjs']);
run('p3a-31',['--test','backend/tests/privateHistoryBoundary.test.mjs']);
run('history-affected',['--test',...['historyAssessmentCutoff.test.js','consumerAwareHistorySelection.test.js','activeHistoricalTemporalProvenance.test.js','consumerAwareHistoricalSelectionPolicy.test.js','scientificHistoryBoundary.test.js','temporalHistorySelection.test.js','temporalEvidencePrimitives.test.js','activeProductTemporalSupport.test.js','remainingTemporalAuthority.test.js','chlorophyllTemporalDerivedFiniteness.test.js'].map(n=>'backend/tests/'+n)]);
if(!process.argv.includes('--focused')){
 // Reuse the already retained independent checkpoint oracle; do not rewrite old evidence.
 assert.equal(hash(fs.readFileSync('.local/ocean-quarantine/cp09b-p1/baseline/backend/p1Oracle.js')),'5a0be577d255a5bdeb29027fb27d64e8a47a062e04703f68f1d8155fb4037409','Independent P1 oracle changed/missing; prepare separately, no replacement');
 if(!process.argv.includes('--remaining'))run('prior-839',['scripts/qualifyCP09Local.mjs',path.join(out,'prior-839')]);
 if(!process.argv.includes('--remaining'))run('p1-44',['--test','backend/tests/retainedBlueMarlinComposition.test.mjs']);
 if(!process.argv.includes('--remaining'))run('p2-60',['--test','--test-isolation=none','backend/tests/retainedInputSupply.test.mjs','backend/tests/postgresRetainedInputSupply.test.mjs']);
 run('p4a-35',['--test','backend/tests/controlledRetainedPublication.test.mjs']);
 const suites=['scientificAssessment.test.js','archiveBoundScienceBoundary.test.js','currentEvidenceCapture.test.js','currentEvidenceCaptureV3.test.js','exactScientificEvidence.test.js','scalarEvidenceHandoff.test.mjs','scalarEvidenceHandoffAdversarial.test.mjs','sstChlorophyllExactReferenceBoundary.test.mjs','oceanConditions.test.js','dynamicOpportunityFailure.test.js','opportunityEvaluationState.test.js','bathymetryEvidence.test.js','publicationEnvelope.test.mjs'];
 const inventory=JSON.parse(fs.readFileSync('backend/tests/sourceNormalizationRegressionProfile.v1.json'));
 for(const suite of suites){const archival=inventory.archiveAssertions.filter(a=>a.file==='backend/tests/'+suite);run('affected-'+suite,['--test',...(archival.length?['--test-skip-pattern=^(?:'+archival.map(a=>RegExp.escape(a.title)).join('|')+')$']:[]),'backend/tests/'+suite]);}
}
for(const [p,h] of Object.entries(fingerprints))assert.equal(hash(fs.readFileSync(p)),h,'Tested bytes changed');
console.log('R9 bounded qualification completed; source fingerprints unchanged.');
