// Fresh final DDL rehearsal inside ROLLBACK; never changes retained local records.
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
import {database,configuration} from '../backend/tests/fixtures/localPublicationFixture.mjs';import {envelope} from '../backend/tests/fixtures/rankedPublicationFixture.mjs';
import {exactJson} from '../backend/exactScientificEvidence.mjs';import {contextKey,byteHash,serializeRankedPublication} from '../backend/durableObserve/publicationEnvelope.mjs';import {cycleV2} from '../shared/oceanPublication.mjs';import {PUBLISHER_FREEZE} from '../backend/durableObserve/publicationScheduler.mjs';import {verifyWorkerPrivileges} from '../backend/durableObserve/privilegeManifest.mjs';
if(process.env.PELORA_CP09_LOCAL!=='1')throw Error('local-opt-in');const db=await database(),h=configuration(),document={contractVersion:PUBLISHER_FREEZE,configurationId:h.c.id,cycleId:cycleV2(h.input.cycle).cycleId,constructedAt:new Date().toISOString(),input:h.input},publication=await envelope(h.input),manifest=JSON.parse(fs.readFileSync(new URL('../backend/durableObserve/publisherPrivilegeManifest.v1.json',import.meta.url))),ddl=fs.readFileSync(new URL('../backend/durableObserve/cp09.sql',import.meta.url),'utf8');
const digest=async()=>{const values=[];for(const name of ['cp08.contexts','cp08.versions','cp08.heads','cp09.configurations','cp09.disables','cp09.jobs','cp09.attempts','cp09.freezes','cp09.submissions','cp09.completions'])values.push([name,(await db.owner.query(`SELECT count(*)::int AS n,encode(sha256(convert_to(coalesce(string_agg(r::text,'' ORDER BY r::text),''),'UTF8')),'hex') AS digest FROM ${name} r`)).rows[0]]);return values;};
try{const local=(await db.owner.query("SELECT current_database() AS db,current_setting('listen_addresses') AS listen,inet_server_port() AS port")).rows[0];assert.equal(local.db,'pelora_phase3_qualification');assert.equal(local.listen,'127.0.0.1');assert.equal(local.port,55432);const before=await digest();let privileges;
 await db.owner.query('BEGIN');try{await db.owner.query('SET LOCAL ROLE pelora_cp02_owner');await db.owner.query('DROP SCHEMA cp09 CASCADE');await db.owner.query('DROP FUNCTION cp08.submit(text)');await db.owner.query('ALTER FUNCTION cp08.submit_internal(text) RENAME TO submit');await db.owner.query(ddl.replace(/^BEGIN;\s*/,'').replace(/COMMIT;\s*$/,''));privileges=await verifyWorkerPrivileges((...a)=>db.owner.query(...a),manifest);
  await db.owner.query('INSERT INTO cp08.contexts VALUES($1,$2)',[contextKey(h.c.context),h.c.context]);const text=exactJson(h.c);await db.owner.query('INSERT INTO cp09.configurations(id,cycle_template_text,record_text,digest,context_key,effective_at,approved_at,clock_mode) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[h.c.id,exactJson({scheduledAt:'__SCHEDULED_AT__',region:h.c.context.region,configuration:h.c.cycleConfiguration}),text,byteHash(text),contextKey(h.c.context),h.c.effectiveAt,h.c.approvedAt,h.c.clockMode]);
  await db.owner.query('SET LOCAL ROLE pelora_cp02_worker');const call=async(op,key,cap,payload)=>(await db.owner.query('SELECT cp09.worker($1,$2,$3,$4) AS value',[op,key,cap,payload])).rows[0].value;const [job]=await call('enumerate',h.c.id,null,h.now),cap=randomUUID(),claim=await call('claim',job,cap,null);assert.equal(claim.status,'OWNED');await call('freeze',job,cap,exactJson({fence:claim.fence,recordText:exactJson(document)}));await call('prepare',job,cap,exactJson({fence:claim.fence,recordText:serializeRankedPublication(publication)}));const accepted=await call('finalize',job,cap,exactJson({fence:claim.fence}));assert.equal(accepted.status,'COMMITTED');assert.equal(accepted.recordText,serializeRankedPublication(publication));
 }finally{await db.owner.query('ROLLBACK');}
 assert.deepEqual(await digest(),before);const report={contractVersion:'pelora-cp09-fresh-ddl-rollback-qualification-v1',status:'PASS',scope:'ISOLATED_CONTROLLED_FIXTURE_ONLY',finalDdlSha256:createHash('sha256').update(ddl).digest('hex'),finalDdlAppliedInRollback:true,workerClaimFreezePrepareFinalizeReadback:true,privileges,originalRecordsExactlyPreserved:true};if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await db.close();}
