create table if not exists public.early_access_signups (
  id bigint generated by default as identity
    primary key,

  email text not null,

  consented_at timestamptz not null
    default now(),

  created_at timestamptz not null
    default now(),

  signup_source text not null
    default 'direct'
    check (
      signup_source in (
        'direct',
        'instagram',
        'facebook',
        'referral',
        'other'
      )
    ),

  status text not null
    default 'active'
    check (
      status in (
        'active',
        'unsubscribed'
      )
    ),

  constraint early_access_signups_email_normalized
    check (
      email = lower(trim(email))
    ),

  constraint early_access_signups_email_format
    check (
      email ~
        '^[A-Za-z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$'
    ),

  constraint early_access_signups_email_unique
    unique (email)
);


alter table public.early_access_signups
  enable row level security;


revoke all
on public.early_access_signups
from anon;


revoke all
on public.early_access_signups
from authenticated;


create or replace function
  public.join_early_access(
    signup_email text,
    signup_source text default 'direct'
  )
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text;
  normalized_source text;
begin
  normalized_email :=
    lower(trim(signup_email));

  normalized_source :=
    lower(trim(signup_source));

  if
    normalized_email is null
    or length(normalized_email) < 3
    or normalized_email !~
      '^[A-Za-z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$'
  then
    raise exception
      'invalid-email';
  end if;


  if
    normalized_source not in (
      'direct',
      'instagram',
      'facebook',
      'referral',
      'other'
    )
  then
    normalized_source :=
      'other';
  end if;


  insert into
    public.early_access_signups (
      email,
      consented_at,
      signup_source,
      status
    )
  values (
    normalized_email,
    now(),
    normalized_source,
    'active'
  )
  on conflict (email)
  do nothing;


  return true;
end;
$$;


revoke all
on function
  public.join_early_access(
    text,
    text
  )
from public;


grant execute
on function
  public.join_early_access(
    text,
    text
  )
to anon;


grant execute
on function
  public.join_early_access(
    text,
    text
  )
to authenticated;


comment on table public.early_access_signups is
  'Private Pelora Early Access signup records. Public clients have no direct table access.';


comment on function public.join_early_access(
  text,
  text
) is
  'Accepts a normalized Pelora Early Access signup without revealing whether the email already exists.';